Sdre
Eigen::MatrixXf* Sdre::phi
Ponteiro da matriz de estado.
Referenced by closeLoopEig, Sdre.
Eigen::MatrixXf* Sdre::gamma
Ponteiro da matriz de controle.
Referenced by closeLoopEig, Sdre.
Riccati* Sdre::ricObj
Ponteiro para o solver da equação de Riccati
Referenced by Controle::Controle, Sdre.
Eigen::MatrixXf* Sdre::R
Matrix ponderação dos controle.
Referenced by Sdre.
Eigen::MatrixXf* Sdre::Q
Matrix ponderação dos estados.
Referenced by Sdre.
Eigen::MatrixXf Sdre::L
Matrix do ganho de Kalman.
Referenced by closeLoopEig, Controle::computeRotationalControl, Controle::Controle, Sdre, updateControl.
Eigen::MatrixXf Sdre::E
Matrix E = B R^-1 B'
Referenced by Sdre, updateControl.
Sdre::Sdre(Eigen::MatrixXf &A, Eigen::MatrixXf &B, Eigen::MatrixXf &Q, Eigen::MatrixXf &R)
: roney : 2021-08-03T17:16:37-03:00 email: roneyddasilva@gmail.com @File: Sdre.cpp Last modified by: roney Last modified time: 2021-08-03T17:16:37-03:00
References E, gamma, L, phi, Q, R, ricObj.
Sdre::~Sdre()
Referenced by Controle::Controle.
bool Sdre::updateControl()
Atualiza a solução de Riccati e o controle ótimo L. true para sucesso ou false para fracasso.
References E, L.
Referenced by Controle::computeRotationalControl, Controle::Controle.
Eigen::MatrixXcf Sdre::closeLoopEig()
[Sdre::closeLoopEig description]
References gamma, L, phi.
Referenced by Controle::Controle.