Controle
Eigen::Vector3f Controle::eulerTarget
Referenced by computeRotationalTarget, xTaskContol.
int Controle::minimalDigitalCommand
Referenced by virtualCommandToMotorCommand, xTaskContol.
int Controle::maximalDigitalCommand
Referenced by virtualCommandToMotorCommand.
float Controle::gravidade
Referenced by computeTranslationalControl, Controle.
uint8_t Controle::index_alt
Referenced by computeRotationalControl, computeRotationalTarget, computeTranslationalControl, xTaskContol.
Drone* Controle::drone
Referenced by xTaskContol.
Sdre* Controle::sdre
Referenced by computeRotationalControl, Controle.
Eigen::Vector3f Controle::r
Referência de velocidade translacional
Referenced by computeTranslationalControl, xTaskContol.
Eigen::Matrix<float, 4, 2> Controle::qa
Quaternion alvo de atitude
Referenced by computeRotationalControl, computeRotationalTarget, Controle, xTaskContol.
Eigen::Vector4f Controle::qe
Quaternio de erro de atitude
Referenced by computeRotationalControl.
Eigen::Vector3f Controle::wa
Velocidade angular alvo
Referenced by computeRotationalControl, computeRotationalTarget, xTaskContol.
float Controle::psi
Ponteiros de velocidade angular Psi alvo
Referenced by computeRotationalTarget, Controle.
float Controle::diffPsi
Velocidade Psi alvo
Referenced by computeRotationalTarget, xTaskContol.
Eigen::Vector3f Controle::rI
Integral da referência de velocidade translacional
Referenced by computeTranslationalControl, xTaskContol.
Eigen::Matrix<float, 3, 6> Controle::Lt
Matriz Ganho de Kalman. u = -L * x da dinâmica translacional
Referenced by computeTranslationalControl, Controle.
Eigen::MatrixXf Controle::Qt
Matriz de ponderação do estado translacional.
Referenced by Controle.
Eigen::MatrixXf Controle::Rt
Matriz de ponderação do controle translacional.
Referenced by Controle.
Eigen::MatrixXf Controle::Rr
Matriz de ponderação do controle rotacional.
Referenced by Controle.
Eigen::MatrixXf Controle::Qr
Matriz de ponderação do estado rotacional.
Referenced by Controle, xTaskContol.
Eigen::Vector3f Controle::ut
Vetor de controle da dinâmica translacional
Referenced by computeRotationalTarget, computeTranslationalControl, Controle, xTaskContol.
Eigen::Vector4f Controle::u
Vetor de tração específica e momentos no corpo. que a tração já esta considerando a massa.
Referenced by computeRotationalControl, computeRotationalTarget, computeTranslationalControl, Controle, virtualCommandToMotorCommand, virtualCommandToMotorRpm, xTaskContol.
Eigen::Vector4i Controle::motorCommands
Comandos digitais
Referenced by virtualCommandToMotorCommand, virtualCommandToMotorRpm, xTaskContol.
Eigen::Vector4f Controle::rotationsOfMotors
Vetor de rotação dos motores
Referenced by virtualCommandToMotorRpm.
float Controle::oldPsi
bool Controle::negative_q0
Referenced by computeRotationalControl, computeRotationalTarget, controlLoop.
float Controle::TSum
Controle::Controle(float discreteTime)
Construct a new Controle:: Controle object.
discreteTime intervalo de tempo de discretização em seconds
References ekf::calc_psi, Sdre::closeLoopEig, Riccati::dareInteration, gravidade, Sdre::L, Lt, PRINT_MAT, psi, qa, Qr, Qt, Sdre::ricObj, Rr, Rt, sdre, u, Sdre::updateControl, ut, Sdre::~Sdre.
void Controle::computeTranslationalControl()
Calcula o controle de translação.
References gravidade, index_alt, Lt, r, rI, u, ut.
Referenced by controlLoop.
void Controle::computeRotationalControl()
Computa do controle da dinâmica rotacional.
References index_alt, Sdre::L, negative_q0, qa, qe, ekf::S_l, sdre, u, Sdre::updateControl, wa.
Referenced by controlLoop.
void Controle::computeRotationalTarget()
References diffPsi, eulerTarget, index_alt, negative_q0, psi, ekf::Q_l, qa, ekf::quaternion2Euler, u, ut, wa.
Referenced by controlLoop.
void Controle::virtualCommandToMotorCommand()
Converte a tração e os momentos em valores digitais de entrada do ESC na classe #Motores.h : Esta funcao limita os
References maximalDigitalCommand, minimalDigitalCommand, motorCommands, u.
Referenced by controlLoop.
void Controle::virtualCommandToMotorRpm()
References motorCommands, rotationsOfMotors, u.
Referenced by controlLoop.
void Controle::controlLoop()
Loop de controle das duas dinâmicas.
References computeRotationalControl, computeRotationalTarget, computeTranslationalControl, negative_q0, virtualCommandToMotorCommand, virtualCommandToMotorRpm.
Referenced by xTaskContol.