TELEMETRIA
uint8_t TELEMETRIA::_broadcast[6][6]
Referenced by begin, envia, enviaMensagem, enviaTunningGains.
struct TELEMETRIA::IMU_DATA TELEMETRIA::imu
Referenced by envia, xTaskLoopFilter.
float TELEMETRIA::gainsTunning[3][3]
Referenced by enviaTunningGains, xTaskContol.
TELEMETRIA::controle
Referenced by OnDataRecv.
uint8_t TELEMETRIA::_quantDados
uint8_t TELEMETRIA::comAceito
Referenced by OnDataRecv.
TELEMETRIA::TELEMETRIA()
Construtor
References begin.
Referenced by OnDataRecv.
void TELEMETRIA::begin()
Inicialização da telemetria
References _broadcast, OnDataRecv.
Referenced by setup, TELEMETRIA.
void TELEMETRIA::envia()
Envia vetor Eigen de float.
quant Dimensão maxima de 20 _a Vetor com dados.
References _broadcast, TELEMETRIA::IMU_DATA::dados, TELEMETRIA::IMU_DATA::dadosEigen, DATA_SIZE, imu.
Referenced by xTaskLoopFilter.
void TELEMETRIA::enviaTunningGains()
References _broadcast, gainsTunning.
Referenced by xTaskContol.
void TELEMETRIA::enviaMensagem(char *aviso)
References _broadcast, TELEMETRIA::MENSAGEM::info.
Referenced by emergencyMethods, setup, xTaskContol, xTaskLoopFilter, xTaskSetupFiltro.
void TELEMETRIA::pisca(uint8_t porta)
struct TELEMETRIA::__attribute__((packed)) controle
void TELEMETRIA::OnDataRecv(const uint8_t *_broadcast, const uint8_t *data, int data_len)
References comAceito, controle, data, TELEMETRIA.
Referenced by begin.