ekf::EKF
const float ekf::EKF::DEG_TO_RAD_BY_10000000
int ekf::EKF::status
Status do filtro
Referenced by begin, xTaskContol, xTaskLoopFilter.
const int ekf::EKF::nAtitude
Número de estados de atitude.
const int ekf::EKF::pAtitude
Número de observações da atitude
BASE ekf::EKF::base
float ekf::EKF::dt
Intervalo de tempo do Loop. Intervalo de tempo para integração da atitude
Referenced by begin.
Eigen::Vector3f ekf::EKF::accel
Vetor com as medidas do acelerometro
Referenced by begin, loop.
const Eigen::Vector3f ekf::EKF::navegationGravity
Gravidade no sistema de navegação
Eigen::Vector3f ekf::EKF::gyro
Vetor com as medidas do giroscopios
Referenced by begin, loop, xTaskContol, xTaskLoopFilter.
Eigen::Vector3f ekf::EKF::mag
Vetor com as medidas do magnetometros
Referenced by begin, loop.
Eigen::Vector4f ekf::EKF::qObs
Vetor com as medias do magnetometro sem as projeções na direção do vetor gravitacional Quaternion de observação
Referenced by begin.
Eigen::Vector4f ekf::EKF::q
Quaternion de atitude
Referenced by begin, drone.Drone.updateStates, xTaskContol, xTaskLoopFilter.
Eigen::Vector3f ekf::EKF::euler
Ângulos de Euler na convenção 3-2-1 Tait-Bryan
Referenced by xTaskLoopFilter.
Eigen::Vector3f ekf::EKF::rNED
Vetor de estados estimados do EKF. O erros são: as três componetes da parte vetorial do quaternion, os três bias do giroscópio e as compoenentes da velocidade no sistema NED. [ q b r] Posicoes no sistema NED
Referenced by xTaskContol.
Eigen::Vector3f ekf::EKF::rNEDgps
Posicao no sistema NED de observação.
Eigen::Vector3f ekf::EKF::drNED
Velocidade linear m/s
Referenced by xTaskContol, xTaskLoopFilter.
Eigen::Vector3f ekf::EKF::drNEDgps
Velocidade linear sistema NED de observação.
Eigen::Vector3f ekf::EKF::ddr
Aceleração linear m/s^2
Eigen::Matrix3f ekf::EKF::mcd
Matrix de cossenos diretores
uint8_t ekf::EKF::messageGPS
int ekf::EKF::p
Número de linhas da matriz H. Assume 3 quando apenas a MARG está disponível e 6 quando MARG/GPS estão disponíveis.
int ekf::EKF::n
Números de estados. q, b_giro, vel, b_accel, posicao
const float ekf::EKF::sigma_giro_squared
Quadrado do desvio padrão do giroscópio.
Referenced by begin.
const float ekf::EKF::sigma_bias_giro_squared
Quadrado do desvio padrão do bias do giroscópio.
Referenced by begin.
const float ekf::EKF::sigma_accel_squared
Quadrado do desvio padrão do acelerômetro.
Referenced by begin.
const float ekf::EKF::sigma_bias_accel_squared
Quadrado do desvio padrão do bias do acelerômetro.
Referenced by begin.
const float ekf::EKF::sigma_aqua_squared
Quadrado do desvio padrão da observação do quatérnion.
Referenced by begin.
const float ekf::EKF::sigma_vel_squared
Quadrado do desvio padrão da velocidade no gps.
const float ekf::EKF::sigma_pos_squared
Quadrado do desvio padrão da posição no gps.
Eigen::Matrix<float, nFull, nFull> ekf::EKF::Q_k
Matriz de covariancia de processo discretizada.
Referenced by begin.
Eigen::Matrix<float, pFull, pFull> ekf::EKF::R
Matriz de covariancia de medidas.
Referenced by begin.
Eigen::Matrix<float, nFull, nFull> ekf::EKF::mF
Matrix de estados linearizada. mF é utilizado como simbolo de F pq F é um simbolo reservado.
Referenced by begin.
Eigen::Matrix<float, nFull, nFull> ekf::EKF::fi
Matriz Jacobiana dos estados.
Eigen::Matrix<float, nFull, 12> ekf::EKF::G
Matriz G de ruido do processo.
Referenced by begin.
Eigen::Matrix<float, nFull, nFull> ekf::EKF::P
Matriz Covariancia
Eigen::Matrix<float, pFull, nFull> ekf::EKF::H
Matriz sensibilidade
Eigen::Matrix<float, nFull, pFull> ekf::EKF::K
Ganho de Kalman
Eigen::Vector<float, nFull + 1> ekf::EKF::deltaChi
Vetor de estados perturbados do estados estimados do EKF. deltaChi possui dimensão 15+1, o primeiro elemento não é calculado pelo filtro mas computado na #updateStates().
Eigen::Vector<float, pFull> ekf::EKF::deltaYObs
Erro das observações
Eigen::Vector3f* ekf::EKF::biasGyro
Observações preditas */ Eigen::VectorXf yPreditas = Eigen::VectorXf::Zero(15); void integrationOfStates(); void updateStates(); void predictionStage(); void updateStage(); void updateF(); void updateFi(); void updateHq(); void updateHv(); void updateHp(); void updateOfMeasurements(); void positionIntegration(); void updateBaseRef(); void updateNedPos(); void updateNedVel(); /*! Vetor ponteiro do bias do giroscópio
Referenced by begin.
Eigen::Vector3f* ekf::EKF::biasAccel
Vetor ponteiro do bias do acelerômetro
Referenced by begin.
const int ekf::EKF::nFull
Número de estados do sistema completo.
const int ekf::EKF::pFull
Número total de observações
ekf::EKF::EKF()
void ekf::EKF::begin(float dt)
Inicializacao do filtro de Kalman.
Inicializa e configura:o GPS, a classe timeClass, instancia os sensores accel, gyro e mag; e Configura os valores padrões da matrizes #F, G e H.
References IMU::_biasAccel, IMU::_biasGyro, accel, ekf::aqua, ekf::BEGIN, TIME::begin, AQUA::begin, IMU::begin, biasAccel, biasGyro, AQUA::computeAQUAQuaternion, dt, G, gpsSetup, gyro, mag, mF, q, Q_k, qObs, R, IMU::readSensor, ekf::READY, sigma_accel_squared, sigma_aqua_squared, sigma_bias_accel_squared, sigma_bias_giro_squared, sigma_giro_squared, status.
Referenced by setup, xTaskSetupFiltro.
void ekf::EKF::loopEKF()
Loop do Filtro de Kalman
Referenced by xTaskLoopFilter.