IMU
GyroRange
AccelRange
DlpfBandwidth
LpAccelOdr
Vector3f* IMU::_acel
Ponteiro das medidas do acelerômetro
Referenced by begin, readSensor.
Vector3f* IMU::_gyro
Ponteiro das medidas do giroscópio
Referenced by begin, calibraGyro, readSensor.
Vector3f* IMU::_mag
Ponteiro das medidas do Magnetômetro
Referenced by begin, readSensor.
Vector3f IMU::magTemp
Referenced by calibracaoMagnetometro, readSensor.
float IMU::_t
const Matrix3f IMU::sFAccel
Matriz fator de escala do acelerometro.
Referenced by readSensor.
Vector3f IMU::_biasAccel
Vetor bias do acelerometro. Atividades futurasA MARG eh capaz de registrar os bias/Offset nos resgistradores. Feito isso as medidas
Referenced by ekf::EKF::begin, readSensor.
Vector3f IMU::_biasGyro
Bias do Giroscópio.
Referenced by ekf::EKF::begin, calibraGyro, readSensor.
Vector3f IMU::_biasMag
Bias do Magnetômetro.
Referenced by calibracaoMagnetometro, readSensor.
Matrix3f IMU::_sM
Matriz fator de escala.
Referenced by calibracaoMagnetometro, readSensor.
TwoWire* IMU::_i2c
Referenced by begin, IMU, readRegisters, writeRegister.
uint8_t IMU::_buffer[21][21]
buffer de leitura do sensor
Referenced by begin, readAK8963Registers, readSensor, whoAmI, whoAmIAK8963, writeAK8963Register, writeRegister.
int16_t IMU::_axcounts
Contadores para leitura das medidas.
Referenced by readSensor.
int16_t IMU::_aycounts
Referenced by readSensor.
int16_t IMU::_azcounts
Referenced by readSensor.
int16_t IMU::_gxcounts
Referenced by readSensor.
int16_t IMU::_gycounts
Referenced by readSensor.
int16_t IMU::_gzcounts
Referenced by readSensor.
int16_t IMU::_hxcounts
Referenced by readSensor.
int16_t IMU::_hycounts
Referenced by readSensor.
int16_t IMU::_hzcounts
Referenced by readSensor.
int16_t IMU::_tcounts
uint8_t IMU::_address
Referenced by IMU, readRegisters, writeRegister.
size_t IMU::_numBytes
numero de bytes para leitura funcao readRegisters
Referenced by readRegisters.
const uint32_t IMU::_i2cRate
int IMU::_status
Referenced by readAK8963Registers.
const float IMU::gG
Referenced by setAccelRange.
float IMU::_accelScale
Referenced by setAccelRange.
float IMU::_gyroScale
Referenced by readSensor, setGyroRange.
float IMU::_magScaleX
Referenced by begin, readSensor.
float IMU::_magScaleY
Referenced by begin.
float IMU::_magScaleZ
Referenced by begin.
AccelRange IMU::_accelRange
Referenced by setAccelRange.
GyroRange IMU::_gyroRange
Referenced by setGyroRange.
DlpfBandwidth IMU::_bandwidth
Referenced by begin, setDlpfBandwidth.
uint8_t IMU::_srd
Referenced by begin.
const uint8_t IMU::ACCEL_OUT
Referenced by readSensor.
const uint8_t IMU::GYRO_OUT
const uint8_t IMU::TEMP_OUT
const uint8_t IMU::EXT_SENS_DATA_00
Referenced by readAK8963Registers.
const uint8_t IMU::ACCEL_CONFIG
Referenced by setAccelRange.
const uint8_t IMU::ACCEL_FS_SEL_2G
Referenced by setAccelRange.
const uint8_t IMU::ACCEL_FS_SEL_4G
Referenced by setAccelRange.
const uint8_t IMU::ACCEL_FS_SEL_8G
Referenced by setAccelRange.
const uint8_t IMU::ACCEL_FS_SEL_16G
Referenced by setAccelRange.
const uint8_t IMU::GYRO_CONFIG
Referenced by setGyroRange.
const uint8_t IMU::GYRO_FS_SEL_250DPS
Referenced by setGyroRange.
const uint8_t IMU::GYRO_FS_SEL_500DPS
Referenced by setGyroRange.
const uint8_t IMU::GYRO_FS_SEL_1000DPS
Referenced by setGyroRange.
const uint8_t IMU::GYRO_FS_SEL_2000DPS
Referenced by setGyroRange.
const uint8_t IMU::ACCEL_CONFIG2
Referenced by setDlpfBandwidth.
const uint8_t IMU::ACCEL_DLPF_184
Referenced by setDlpfBandwidth.
const uint8_t IMU::ACCEL_DLPF_92
Referenced by setDlpfBandwidth.
const uint8_t IMU::ACCEL_DLPF_41
Referenced by setDlpfBandwidth.
const uint8_t IMU::ACCEL_DLPF_20
Referenced by setDlpfBandwidth.
const uint8_t IMU::ACCEL_DLPF_10
Referenced by setDlpfBandwidth.
const uint8_t IMU::ACCEL_DLPF_5
Referenced by setDlpfBandwidth.
const uint8_t IMU::CONFIG
Referenced by setDlpfBandwidth.
const uint8_t IMU::GYRO_DLPF_184
Referenced by setDlpfBandwidth.
const uint8_t IMU::GYRO_DLPF_92
Referenced by setDlpfBandwidth.
const uint8_t IMU::GYRO_DLPF_41
Referenced by setDlpfBandwidth.
const uint8_t IMU::GYRO_DLPF_20
Referenced by setDlpfBandwidth.
const uint8_t IMU::GYRO_DLPF_10
Referenced by setDlpfBandwidth.
const uint8_t IMU::GYRO_DLPF_5
Referenced by setDlpfBandwidth.
const uint8_t IMU::SMPDIV
Referenced by begin.
const uint8_t IMU::INT_PIN_CFG
const uint8_t IMU::INT_ENABLE
const uint8_t IMU::INT_DISABLE
const uint8_t IMU::INT_PULSE_50US
const uint8_t IMU::INT_WOM_EN
const uint8_t IMU::INT_RAW_RDY_EN
const uint8_t IMU::PWR_MGMNT_1
Referenced by begin.
const uint8_t IMU::PWR_CYCLE
const uint8_t IMU::PWR_RESET
Referenced by begin.
const uint8_t IMU::CLOCK_SEL_PLL
Referenced by begin.
const uint8_t IMU::PWR_MGMNT_2
Referenced by begin.
const uint8_t IMU::SEN_ENABLE
Referenced by begin.
const uint8_t IMU::DIS_GYRO
const uint8_t IMU::USER_CTRL
Referenced by begin.
const uint8_t IMU::I2C_MST_EN
Referenced by begin.
const uint8_t IMU::I2C_MST_CLK
Referenced by begin.
const uint8_t IMU::I2C_MST_CTRL
Referenced by begin.
const uint8_t IMU::I2C_SLV0_ADDR
Referenced by readAK8963Registers, writeAK8963Register.
const uint8_t IMU::I2C_SLV0_REG
Referenced by readAK8963Registers, writeAK8963Register.
const uint8_t IMU::I2C_SLV0_DO
Referenced by writeAK8963Register.
const uint8_t IMU::I2C_SLV0_CTRL
Referenced by readAK8963Registers, writeAK8963Register.
const uint8_t IMU::I2C_SLV0_EN
Referenced by readAK8963Registers, writeAK8963Register.
const uint8_t IMU::I2C_READ_FLAG
Referenced by readAK8963Registers.
const uint8_t IMU::MOT_DETECT_CTRL
const uint8_t IMU::ACCEL_INTEL_EN
const uint8_t IMU::ACCEL_INTEL_MODE
const uint8_t IMU::LP_ACCEL_ODR
const uint8_t IMU::WOM_THR
const uint8_t IMU::WHO_AM_I
Referenced by whoAmI.
const uint8_t IMU::AK8963_I2C_ADDR
Referenced by readAK8963Registers, writeAK8963Register.
const uint8_t IMU::AK8963_HXL
Referenced by begin.
const uint8_t IMU::AK8963_CNTL1
Referenced by begin.
const uint8_t IMU::AK8963_PWR_DOWN
Referenced by begin.
const uint8_t IMU::AK8963_CNT_MEAS1
const uint8_t IMU::AK8963_CNT_MEAS2
Referenced by begin.
const uint8_t IMU::AK8963_FUSE_ROM
Referenced by begin.
const uint8_t IMU::AK8963_CNTL2
Referenced by begin.
const uint8_t IMU::AK8963_RESET
Referenced by begin.
const uint8_t IMU::AK8963_ASA
Referenced by begin.
const uint8_t IMU::AK8963_WHO_AM_I
Referenced by whoAmIAK8963.
IMU::IMU(TwoWire &bus, uint8_t address)
Construtor da classe IMU. bus classe de comunicacao Wire. address Endereço do imu.
References _address, _i2c.
int IMU::begin(Vector3f &acel, Vector3f &gyro, Vector3f &mag)
Inicialização e configuração da unidade MARG. acel Vetor de medidas do acelerômetro. gyro Vetor de medidas do giroscópio. mag Vetor de medidas do Magnetômetro. inteiro positivo para ok ou negativo para erros.
References _acel, _bandwidth, _buffer, _gyro, _i2c, _mag, _magScaleX, _magScaleY, _magScaleZ, _srd, ACCEL_RANGE_16G, AK8963_ASA, AK8963_CNT_MEAS2, AK8963_CNTL1, AK8963_CNTL2, AK8963_FUSE_ROM, AK8963_HXL, AK8963_PWR_DOWN, AK8963_RESET, CLOCK_SEL_PLL, DLPF_BANDWIDTH_5HZ, GYRO_RANGE_1000DPS, I2C_MST_CLK, I2C_MST_CTRL, I2C_MST_EN, PWR_MGMNT_1, PWR_MGMNT_2, PWR_RESET, readAK8963Registers, SEN_ENABLE, setAccelRange, setDlpfBandwidth, setGyroRange, SMPDIV, USER_CTRL, whoAmIAK8963, writeAK8963Register, writeRegister.
Referenced by ekf::EKF::begin.
int IMU::readSensor()
Faz leitura da MARG. Positivo se ok, negativo para ok contrário. As variáveis _acel, _gyro e _mag são modificadas.
References _acel, _axcounts, _aycounts, _azcounts, _biasAccel, _biasGyro, _biasMag, _buffer, _gxcounts, _gycounts, _gyro, _gyroScale, _gzcounts, _hxcounts, _hycounts, _hzcounts, _mag, _magScaleX, _sM, ACCEL_OUT, magTemp, readRegisters, sFAccel.
Referenced by ekf::EKF::begin, calibracaoMagnetometro, calibraGyro.
int IMU::setDlpfBandwidth(DlpfBandwidth bandwidth)
Configura a o filtro passa baixa do acelerômetro e do giroscópio. bandwidth de operação positivo se ok, negativo se falhar.
References _bandwidth, ACCEL_CONFIG2, ACCEL_DLPF_10, ACCEL_DLPF_184, ACCEL_DLPF_20, ACCEL_DLPF_41, ACCEL_DLPF_5, ACCEL_DLPF_92, CONFIG, DLPF_BANDWIDTH_10HZ, DLPF_BANDWIDTH_184HZ, DLPF_BANDWIDTH_20HZ, DLPF_BANDWIDTH_41HZ, DLPF_BANDWIDTH_5HZ, DLPF_BANDWIDTH_92HZ, GYRO_DLPF_10, GYRO_DLPF_184, GYRO_DLPF_20, GYRO_DLPF_41, GYRO_DLPF_5, GYRO_DLPF_92, writeRegister.
Referenced by begin.
int IMU::setGyroRange(GyroRange range)
Configura a sensibilidade de operação do giroscópio. range de operação positivo se ok, negativo se falhar.
References _gyroRange, _gyroScale, GYRO_CONFIG, GYRO_FS_SEL_1000DPS, GYRO_FS_SEL_2000DPS, GYRO_FS_SEL_250DPS, GYRO_FS_SEL_500DPS, GYRO_RANGE_1000DPS, GYRO_RANGE_2000DPS, GYRO_RANGE_250DPS, GYRO_RANGE_500DPS, writeRegister.
Referenced by begin.
int IMU::setAccelRange(AccelRange range)
Configura a sensibilidade de operação do acelerômetro. range de operação positivo se ok, negativo se falhar.
References _accelRange, _accelScale, ACCEL_CONFIG, ACCEL_FS_SEL_16G, ACCEL_FS_SEL_2G, ACCEL_FS_SEL_4G, ACCEL_FS_SEL_8G, ACCEL_RANGE_16G, ACCEL_RANGE_2G, ACCEL_RANGE_4G, ACCEL_RANGE_8G, gG, writeRegister.
Referenced by begin.
void IMU::calibraGyro(int N=100)
Método de calibração do giroscópio. N número de dados coletados para computodo da média Compensa-se o erro sistemático eliminando calculando a medida de #N medidas. O valor compensando é dado por gyro_c = _gyroScale*(gyro_m - _biasGyro)
References _biasGyro, _gyro, readSensor.
int IMU::calibracaoMagnetometro(float moduloCampo)
References _biasMag, _sM, METODOSCALIBRACAO::calibracaoGeometrica, magTemp, readSensor.
int IMU::writeRegister(uint8_t subAddress, uint8_t data)
Escreve nos registros da Marg subAddress data Esada para ler os dados e configurar a MARG.
References _address, _buffer, _i2c, data, readRegisters.
Referenced by begin, readAK8963Registers, setAccelRange, setDlpfBandwidth, setGyroRange, writeAK8963Register.
int IMU::readRegisters(uint8_t subAddress, uint8_t count, uint8_t *dest)
Leitura dos registros da MARG subAddress count dest positivo se ok, negativo para o contrário.
References _address, _i2c, _numBytes.
Referenced by readAK8963Registers, readSensor, whoAmI, writeRegister.
int IMU::writeAK8963Register(uint8_t subAddress, uint8_t data)
References _buffer, AK8963_I2C_ADDR, data, I2C_SLV0_ADDR, I2C_SLV0_CTRL, I2C_SLV0_DO, I2C_SLV0_EN, I2C_SLV0_REG, readAK8963Registers, writeRegister.
Referenced by begin.
int IMU::whoAmI()
Checa o registro de um dispositivo. usado para o acelerômetro e giroscópio.
References _buffer, readRegisters, WHO_AM_I.
int IMU::whoAmIAK8963()
Verifica se o Magnetômetro está ok.
References _buffer, AK8963_WHO_AM_I, readAK8963Registers.
Referenced by begin.
int IMU::readAK8963Registers(uint8_t subAddress, uint8_t count, uint8_t *dest)
References _buffer, _status, AK8963_I2C_ADDR, EXT_SENS_DATA_00, I2C_READ_FLAG, I2C_SLV0_ADDR, I2C_SLV0_CTRL, I2C_SLV0_EN, I2C_SLV0_REG, readRegisters, writeRegister.
Referenced by begin, whoAmIAK8963, writeAK8963Register.