IBusBM
State
volatile uint8_t IBusBM::cnt_poll
Referenced by loop.
volatile uint8_t IBusBM::cnt_sensor
Referenced by loop.
volatile uint8_t IBusBM::cnt_rec
Referenced by loop.
ControlUnion IBusBM::remoteControl
Referenced by emergencyMethods, loop, readChannel, setup, xTaskContol, xTaskSetupFiltro.
const uint8_t IBusBM::PROTOCOL_LENGTH
const uint8_t IBusBM::PROTOCOL_OVERHEAD
Referenced by loop.
const uint8_t IBusBM::PROTOCOL_TIMEGAP
Referenced by loop.
const uint8_t IBusBM::PROTOCOL_CHANNELS
Referenced by loop, readChannel.
const uint8_t IBusBM::PROTOCOL_COMMAND40
Referenced by loop.
const uint8_t IBusBM::PROTOCOL_COMMAND_DISCOVER
Referenced by loop.
const uint8_t IBusBM::PROTOCOL_COMMAND_TYPE
Referenced by loop.
const uint8_t IBusBM::PROTOCOL_COMMAND_VALUE
Referenced by loop.
const uint8_t IBusBM::SENSORMAX
Referenced by addSensor.
uint8_t IBusBM::state
Referenced by begin, loop.
HardwareSerial* IBusBM::stream
Referenced by begin, loop.
uint32_t IBusBM::last
Referenced by begin, loop.
uint8_t IBusBM::buffer[PROTOCOL_LENGTH][PROTOCOL_LENGTH]
Referenced by loop.
uint8_t IBusBM::ptr
Referenced by begin, loop.
uint8_t IBusBM::len
Referenced by addSensor, begin, loop.
uint16_t IBusBM::chksum
Referenced by begin, loop.
uint8_t IBusBM::lchksum
Referenced by begin, loop.
sensorinfo IBusBM::sensors[SENSORMAX][SENSORMAX]
Referenced by addSensor, loop, setSensorMeasurement.
uint8_t IBusBM::NumberSensors
Referenced by addSensor.
IBusBM* IBusBM::IBusBMnext
Referenced by begin, loop.
void IBusBM::begin(HardwareSerial &serial, int8_t timerid=0, int8_t rxPin=-1, int8_t txPin=-1)
References chksum, DISCARD, IBUSBM_NOTIMER, IBusBMfirst, IBusBMnext, last, lchksum, len, onTimer, ptr, state, stream.
Referenced by setup.
uint16_t IBusBM::readChannel(uint8_t channelNr)
References IBusBM::ControlUnion::channel, PROTOCOL_CHANNELS, remoteControl.
uint8_t IBusBM::addSensor(uint8_t type, uint8_t len=2)
References len, NumberSensors, IBusBM::sensorinfo::sensorLength, SENSORMAX, sensors, IBusBM::sensorinfo::sensorType, IBusBM::sensorinfo::sensorValue.
void IBusBM::setSensorMeasurement(uint8_t adr, int32_t value)
References sensors, IBusBM::sensorinfo::sensorValue.
void IBusBM::loop(void)
References buffer, IBusBM::ControlUnion::channel, chksum, cnt_poll, cnt_rec, cnt_sensor, DISCARD, GET_CHKSUMH, GET_CHKSUML, GET_DATA, GET_LENGTH, IBusBMnext, last, lchksum, len, loop, PROTOCOL_CHANNELS, PROTOCOL_COMMAND40, PROTOCOL_COMMAND_DISCOVER, PROTOCOL_COMMAND_TYPE, PROTOCOL_COMMAND_VALUE, PROTOCOL_OVERHEAD, PROTOCOL_TIMEGAP, ptr, remoteControl, IBusBM::sensorinfo::sensorLength, sensors, IBusBM::sensorinfo::sensorType, IBusBM::sensorinfo::sensorValue, state, stream.
Referenced by emergencyMethods, loop, onTimer, setup, xTaskContol, xTaskSetupFiltro.