Rpm
int16_t Rpm::rpm
Referenced by update_rpm.
int8_t Rpm::ciclos_por_volta
Referenced by Rpm.
const int16_t Rpm::MAX_H_LIM
Referenced by init, Rpm.
uint32_t Rpm::rpm_factor
Referenced by Rpm, update_rpm.
pcnt_unit_t Rpm::pcnt_unit
Referenced by get_pulses, init, restart_conter, Rpm.
int16_t Rpm::pulses
Referenced by get_pulses, init.
gpio_num_t Rpm::sensor
Referenced by init, Rpm.
uint64_t Rpm::time_array[2][2]
Referenced by init, update_rpm.
uint8_t Rpm::index_time_array
Referenced by init, update_rpm.
uint32_t Rpm::dt
Referenced by update_rpm.
Rpm::Rpm(gpio_num_t sensor, pcnt_unit_t pcnt_unit=PCNT_UNIT_0, uint8_t ciclos_por_volta=1)
References ciclos_por_volta, init, MAX_H_LIM, pcnt_unit, pointer_Rpm, rpm_factor, sensor.
void Rpm::update_rpm()
References dt, index_time_array, rpm, rpm_factor, time_array.
Referenced by init, outside_interrupt_handler.
void Rpm::restart_conter()
References pcnt_unit.
Referenced by init.
void Rpm::get_pulses()
References pcnt_unit, pulses.
void Rpm::init()
References index_time_array, MAX_H_LIM, pcnt_unit, pulses, restart_conter, sensor, time_array, update_rpm.
Referenced by Rpm.