Motores
gpio_num_t Motores::motor_pin
pino do motor
Referenced by Motores, set_portas.
uint8_t Motores::canal
Canal utilizado pelo motor.
Referenced by calibra, inicializa, Motores, set_portas, set_vel_mot.
const uint16_t Motores::tempo_calibracao
Tempo para calibracao entre atribuicao de minimo e maximo. milli segundos]
Referenced by calibra.
const uint16_t Motores::resolucao
Resolucao do controle PWM.
Referenced by inicializa, Motores.
const double Motores::freq
Frequencia do PWM de controle.
Referenced by inicializa, Motores.
uint16_t Motores::min_vel
Minimo valor do duty cycle
Referenced by calibra, inicializa, Motores.
uint16_t Motores::max_vel
Maximo valor do duty cycle
Referenced by calibra, Motores.
Motores::Motores(gpio_num_t motor_pin, uint8_t canal=0)
Construtor da classe motor.
motor_pin GPIO que ESC esta conectado canal que o PWM sera conectado
References canal, freq, inicializa, max_vel, min_vel, motor_pin, resolucao.
void Motores::inicializa()
configuracao das frequencias PWM que o esc's utilizam.
References canal, freq, min_vel, resolucao, set_portas, set_vel_mot.
Referenced by Motores.
void Motores::set_portas()
References canal, motor_pin.
Referenced by inicializa.
void Motores::calibra()
Rotina de calibração dos motores.
References canal, max_vel, min_vel, tempo_calibracao.
void Motores::set_vel_mot(uint16_t vel)
funcao que muda a velocidade.
vel inteiro que possui valor entre min_vel e max_vel
References canal.
Referenced by inicializa, xTaskContol.