AQUA
Eigen::Vector4f AQUA::qAcc
Quaternion de inclinacao.
Referenced by computeAQUAQuaternion, computeQuaternionAccel.
Eigen::Vector4f AQUA::qMag
Quaternion de Guinada.
Referenced by computeAQUAQuaternion, computeQuaternionMag.
Eigen::Vector3f AQUA::gravNormalized
Campo gravitacional normalizado no sistema do corpo
Referenced by computeAQUAQuaternion, computeQuaternionAccel.
Eigen::Vector3f AQUA::magNormalized
Campo magnetico normalizado no sistema do corpo
Referenced by computeAQUAQuaternion.
Eigen::Vector3f AQUA::l
Campo magnetico expresso no sistema intermediario
Referenced by computeAQUAQuaternion, computeQuaternionMag.
Eigen::Vector4f* AQUA::qAQUA
Ponteiro do quaternion de atititude.
Referenced by begin, computeAQUAQuaternion.
Eigen::Vector3f* AQUA::accel
Ponteiros do acelerometro e do magnetometro
Referenced by begin.
Eigen::Vector3f * AQUA::mag
Referenced by begin.
AQUA::AQUA()
Intância da classe AQUA.
void AQUA::begin(Eigen::Vector4f &_qObs, Eigen::Vector3f &accel, Eigen::Vector3f &mag)
References accel, mag, qAQUA.
Referenced by ekf::EKF::begin.
int AQUA::computeAQUAQuaternion()
Calcula o quaternion de atitude com o algoritimo AQUA. acel Vetor de medidas do acelerometro mag Vetor de medidas do magnetometro 0 se falhar ou 1 se sucesso.
References computeQuaternionAccel, computeQuaternionMag, gravNormalized, l, magNormalized, ekf::multiplyQuaternions, qAcc, qAQUA, qMag, ekf::rotateVectorWithQuaternion_Conjugate.
Referenced by ekf::EKF::begin.
void AQUA::computeQuaternionAccel()
Calcula o quaternion de inclinacao.
References gravNormalized, INVERSE_SQUARE_2, qAcc.
Referenced by computeAQUAQuaternion.
void AQUA::computeQuaternionMag()
Computa o quaternion de guinada.
References INVERSE_SQUARE_2, ekf::invSqrt, l, qMag.
Referenced by computeAQUAQuaternion.