GPS.h
NAV_PVT
NAV_POSECEF
RATE_10
NAV_MODE_1G
_ubxMsgType
const unsigned char UBX_HEADER[][]
Referenced by processGPS.
const unsigned char NAV_POSECEF_HEADER[][]
Referenced by processGPS.
const unsigned char NAV_PVT_HEADER[][]
Referenced by processGPS.
PacketData data
Referenced by METODOSCALIBRACAO::calibracaoAcelerometro, METODOSCALIBRACAO::calibracaoGeometrica, TELEMETRIA::OnDataRecv, IMU::writeAK8963Register, IMU::writeRegister.
UBXMessage ubxMessage
Referenced by calcChecksum, compareMsgHeader, gps_imprime, processGPS.
HardwareSerial GPSSERIAL(1)
Referenced by gps_imprime, gpsSetup, processGPS.
void gpsSetup()
References GPSSERIAL.
Referenced by ekf::EKF::begin.
void calcChecksum(unsigned char *CK, int msgSize)
References ubxMessage.
Referenced by processGPS.
boolean compareMsgHeader(const unsigned char *msgHeader)
References ubxMessage.
Referenced by processGPS.
int processGPS()
References calcChecksum, compareMsgHeader, GPSSERIAL, MT_NAV_POSECEF, MT_NAV_PVT, MT_NONE, NAV_POSECEF_HEADER, NAV_PVT_HEADER, UBX_HEADER, ubxMessage.
Referenced by gps_imprime.
void gps_imprime()
References NAV_POSECEF_STRUCT::ecefX, NAV_POSECEF_STRUCT::ecefY, NAV_POSECEF_STRUCT::ecefZ, NAV_PVT_STRUCT::fixType, GPSSERIAL, NAV_PVT_STRUCT::hMSL, NAV_POSECEF_STRUCT::iTOW, NAV_PVT_STRUCT::iTOW, NAV_PVT_STRUCT::lat, NAV_PVT_STRUCT::lon, MT_NAV_POSECEF, MT_NAV_PVT, UBXMessage::navPosecef, UBXMessage::navPvt, processGPS, ubxMessage, NAV_PVT_STRUCT::velD, NAV_PVT_STRUCT::velE, NAV_PVT_STRUCT::velN.