main.cpp
DEBUG_MAIN
PM
CALIBRATION_OF_MAGNETOMETER_GYROSCOPE
IBusBM iBus
Referenced by emergencyMethods, setup, xTaskContol, xTaskSetupFiltro.
Vector3f* eulerTarget
Referenced by xTaskContol.
Vector3f * ra
Referenced by xTaskContol, xTaskLoopFilter.
Vector3f * wa
Referenced by xTaskContol, xTaskLoopFilter.
Vector3f * rI
Referenced by xTaskContol.
Vector3f qa
Referenced by xTaskContol, xTaskLoopFilter.
Vector4f* moments
Referenced by xTaskContol.
Vector4i* comandosDigitais
Referenced by xTaskContol.
TELEMETRIA tel
Referenced by emergencyMethods, setup, xTaskContol, xTaskLoopFilter, xTaskSetupFiltro.
TaskHandle_t xHandleSetupFilter
Referenced by setup.
TaskHandle_t xHandleLoopFilter
Referenced by xTaskSetupFiltro.
TaskHandle_t xHandleControl
Referenced by emergencyMethods, setup.
TaskHandle_t xHandleEmergency
void xTaskLoopFilter(void *)
References TELEMETRIA::IMU_DATA::dadosEigen, ekf::EKF::drNED, TELEMETRIA::envia, TELEMETRIA::enviaMensagem, ekf::EKF::euler, ekf::EKF::gyro, TELEMETRIA::imu, ekf::EKF::loopEKF, ekf::EKF::q, qa, ekf::quaternion2Euler, ra, ekf::READY, ekf::EKF::status, tel, wa, xdtTelemetry.
Referenced by xTaskSetupFiltro.
void xTaskSetupFiltro(void *pvParameters)
References ekf::EKF::begin, IBusBM::ControlUnion::calibration, dtTelemetry, TELEMETRIA::enviaMensagem, iBus, IBusBM::loop, IBusBM::remoteControl, tel, xHandleLoopFilter, xTaskLoopFilter.
Referenced by setup.
void emergencyMethods(void *pv)
Task de Procedimentos emergenciais.
References IBusBM::ControlUnion::emergency, TELEMETRIA::enviaMensagem, iBus, IBusBM::loop, IBusBM::remoteControl, tel, turnOffLed, turnOnLed, xHandleControl.
Referenced by xTaskContol.
void xTaskContol(void *pv)
References IBusBM::ControlUnion::adjustQrAngular, IBusBM::ControlUnion::adjustQuat, comandosDigitais, Controle::controlLoop, Controle::diffPsi, IBusBM::ControlUnion::dPsi, ekf::EKF::drNED, Controle::drone, dtControle, IBusBM::ControlUnion::dX, IBusBM::ControlUnion::dY, IBusBM::ControlUnion::dZ, IBusBM::ControlUnion::emergency, emergencyMethods, TELEMETRIA::enviaMensagem, TELEMETRIA::enviaTunningGains, Controle::eulerTarget, eulerTarget, TELEMETRIA::gainsTunning, ekf::EKF::gyro, iBus, Controle::index_alt, IBusBM::loop, Controle::minimalDigitalCommand, moments, MOTOR_PINS::motor_1, MOTOR_PINS::motor_2, MOTOR_PINS::motor_3, MOTOR_PINS::motor_4, Controle::motorCommands, Drone::p, Drone::q, ekf::EKF::q, Controle::qa, qa, Controle::Qr, Controle::r, ra, ekf::READY, IBusBM::remoteControl, Controle::rI, rI, ekf::EKF::rNED, Motores::set_vel_mot, ekf::EKF::status, tel, Controle::u, Controle::ut, Drone::v, Drone::w, Controle::wa, wa, xdtControle.
Referenced by setup.
void setup()
References TELEMETRIA::begin, ekf::EKF::begin, IBusBM::begin, dtTelemetry, IBusBM::ControlUnion::emergency, TELEMETRIA::enviaMensagem, iBus, IBUSBM_NOTIMER, IBusBM::loop, onboard_led, pin_rx_controle, IBusBM::remoteControl, tel, xHandleControl, xHandleSetupFilter, xTaskContol, xTaskSetupFiltro.
void loop()
References ekf::EKF::accel, ekf::EKF::gyro, ekf::EKF::mag, PM.