funcoesQuaternion
def funcoesQuaternion.screwMatrix(quat)
Computa a matriz anti-simetrica a partir do quaternion quat. Parameters ---------- quat : quanternio de atitude. Returns ------- q_x : 3x3 matrix anti-simetrica
Referenced by matrixQ, rotationMatrix.
def funcoesQuaternion.matrixQ(quat, right=False)
Compute Q matrix. Parameters ---------- quat : quaternion orientation 4x1 right : boolean. The default is False. Returns ------- Q : Q matrix.
References screwMatrix.
Referenced by matrixS.
def funcoesQuaternion.matrixS(quat, right=False)
Compute S matrix. Parameters ---------- quat : quaternion 4x1. right : boolean, optional. The default is False. Returns ------- S : Matrix S.
References matrixQ.
def funcoesQuaternion.MultQuat(r, q, p)
Parameters. r, q : quaternion attitude input. p : result of multiplication.
def funcoesQuaternion.conj(q)
Retorna o conjugado do quaternion q. Parameters ---------- q : quaternion de atitude. Returns ------- p : conjugado do quaternion de atitude q.
def funcoesQuaternion.quat2Euler(q, deg=0)
Parameters. q : quaternion attitude. deg : TYPE, optional DESCRIPTION. 1 to return in degrees. The default is 0. Returns ------- TYPE DESCRIPTION. e : 3x1 euler angles
def funcoesQuaternion.rotationMatrix(q)
Computa a matriz de rotacao a partir do quaternio de attitude. Parameters ---------- q : quaternion de atitude. Returns ------- Matrix de rotacao
References screwMatrix.
def funcoesQuaternion.eulerQuaternion(yaw, pitch, roll, deg=True)
Calcula o quaternio a partir dos Angulos de Euler. Parameters ---------- yaw : angulo de guinad [rad] pitch : angulo de guinad [rad] roll : angulo de guinad [rad] deg : se 1 informa que os angulos estao em graus q : quaternio atitude