ekf
_status
AQUA ekf::aqua
Classe do filtro de Kalman.
Referenced by ekf::EKF::begin.
const float ekf::TOLERANCE
Referenced by integrationQuaternion.
Eigen::MatrixXf ekf::Q_r(const Eigen::Ref< Eigen::Vector4f > &q)
Matrix Right-Quaternion Q q quaternion de atitude Matrix Right Quarternio Q
References skew.
Eigen::MatrixXf ekf::Q_l(const Eigen::Ref< Eigen::Vector4f > &q)
Matrix Left-Quaternion Q q quaternion de atitude Matrix Left Quarternio Q
References skew.
Referenced by Controle::computeRotationalTarget.
Eigen::Matrix3f ekf::skew(const Eigen::Vector3f &v)
Matrix antissimetrica.
[v] Vetor tridimensional [M] Matrix antissimetrica A matrix antissimetrica torna possivel converter um produto vetorial em produto de matrizes.
Referenced by computeMcdFromQuaternion, Q_l, Q_r, S_l, S_r, Drone::updateStateMatrices.
Eigen::Matrix4f ekf::S_r(const Eigen::Ref< Eigen::Vector4f > q)
Calcula a Matriz Right-Quaternion a partir do quaternion q.
q quaternion de atitude mS_r Matrix Right-Quaternion A matrix Right-Quaternion torna possível realizar o produto de quaternions como um produto matricial comum.
References skew.
Eigen::Matrix4f ekf::S_l(const Eigen::Ref< Eigen::Vector4f > &q)
Calcula a Matriz Left-Quaternion a partir do quaternion q.
q quaternion de atitude mS_l Matrix Right-Quaternion A matrix Left-Quaternion torna possível realizar o produto de quaternions como um produto matricial comum.
References skew.
Referenced by Controle::computeRotationalControl.
void ekf::computeMcdFromQuaternion(const Eigen::Vector4f &q, Eigen::Matrix3f &mcd)
Calcula a matriz de cossenos ditores a parir do quaternion de atitude q quaternion de atitude mcd Matriz de cossenos diretores a ser atualizada (Referencia)
References skew.
void ekf::printEigen(const Eigen::MatrixXf &m)
Imprime um dado Eigen. Matriz ou vetor. m dado a ser impresso.
References drone.m.
Eigen::Vector3f ekf::computeVectorProjection(const Eigen::Ref< Eigen::Vector3f > &v, const Eigen::Ref< Eigen::Vector3f > &u)
Rejeita a projecao do vetor v sobre u . u Vetor tridimensional v Vetor tridimensional v sem a projeção de v sobre u. * Vector Rejection [Vector Rejection ]
Eigen::Vector4f ekf::multiplyQuaternions(const Eigen::Ref< Eigen::VectorXf > &p, const Eigen::Ref< Eigen::VectorXf > &q)
Produto de quaternions aplicado.
p Quaternion q Vetor tridimensional Quaternion product pq
Referenced by AQUA::computeAQUAQuaternion, integrationQuaternion.
void ekf::quaternion2Euler(Eigen::Ref< Eigen::Vector3f > _euler, const Eigen::Ref< const Eigen::Vector4f > &_q)
References calc_phi, calc_psi, calc_theta.
Referenced by Controle::computeRotationalTarget, xTaskLoopFilter.
void ekf::calc_phi(float &x, const Eigen::Ref< const Eigen::Vector4f > &_q)
Calcula, a partir de um quatérnio de atitude, o valor do ângulo Phi em Radianos.
x Referencia a ser sobrescrita. -pi < x < pi _q Quaternion de atitude
Referenced by quaternion2Euler.
void ekf::calc_theta(float &x, const Eigen::Ref< const Eigen::Vector4f > &_q)
Calcula, a partir de um quatérnio de atitude, o valor do ângulo Theta em Radianos.
x Referencia a ser sobrescrita. -pi/2 < x < pi/2 _q Quaternion de atitude
Referenced by quaternion2Euler.
void ekf::calc_psi(float &x, const Eigen::Ref< const Eigen::Vector4f > &_q)
Calcula, a partir de um quatérnio de atitude, o valor do ângulo Psi em Radianos.
x Referencia a ser sobrescrita. -pi < x < pi _q Quaternion de atitude
Referenced by Controle::Controle, quaternion2Euler.
void ekf::integrationQuaternion(Eigen::Vector4f &_quat, const Eigen::Ref< const Eigen::VectorXf > &_gyroscope, float &_dt)
References multiplyQuaternions, TOLERANCE.
Eigen::Vector3f ekf::rotateVectorWithQuaternion(Eigen::Vector4f &q, Eigen::Vector3f &v_old)
Rotaciona um vetor tridimensional com um quaternion.
q quaternion de atitude v_old vetor a ser rotacionado v_new vetor rotacionado. A transformação desta forma possui 30 operações (15 produtos e 15 multiplicações.)(Rotacao de vetor tridimensional com formalismo de eixo/angulo)[https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation#Performance_comparisons]
Eigen::Vector3f ekf::rotateVectorWithQuaternion_Conjugate(Eigen::Vector4f &q, Eigen::Vector3f &v_old)
Rotaciona um vetor tridimensional com um quaternion conjugado.
q quaternion de atitude v_old vetor a ser rotacionado v_new vetor rotacionado. A trasnfromação desta forma possui 30 operações (15 produtos e 15 multiplicações.)(Rotacao de vetor tridimensional com formalismo de eixo/angulo)[https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation#Performance_comparisons]
Referenced by AQUA::computeAQUAQuaternion.
float ekf::invSqrt(float _x)
Calcula o inverso do raiz de um float.
Para mais detalhes consulte Fast inverse square-root _x 1/sqrt(_x)
Referenced by AQUA::computeQuaternionMag.
Eigen::Vector4f ekf::q_theta(float &phi)
Calcula o quaternion de atitude de rotação phi sobre o eixo x.
phi Eigen::Vector4f Quaternion de rotacao phi
Eigen::Vector4f ekf::q_phi(float &theta)
Calcula o quaternion de atitude de rotação theta sobre o eixo y.
theta Eigen::Vector4f Quaternion de rotacao theta
Eigen::Vector4f ekf::q_psi(float &psi)
Calcula o quaternion de atitude de rotação psi sobre o eixo z.
psi Eigen::Vector4f Quaternion de rotacao psi
void ekf::computeQuaternionFromMCDMarkley(Eigen::Matrix3f &m, Eigen::Ref< Eigen::Vector4f > q)
Extrai o quatérnio a partir da matrix de cossenos diretores. m Matrix de cossenos diretores. q Quaternion de atitude. Utiza o algoritmo BUG
References drone.m.
Eigen::VectorXf ekf::RK(float h, const Eigen ::Ref< Eigen::VectorXf > &xk, const Eigen ::Ref< Eigen::VectorXf > &u, Eigen::VectorXf(fn)(Eigen::VectorXf x, Eigen::VectorXf u))
void ekf::conjugate(Eigen::Ref< Eigen::Vector4f > _q)
Conjuga o quaternion _q.
_q
Eigen::Matrix4f ekf::S_r(const Eigen::Ref< Eigen::Vector4f > &q)
void ekf::computeQuaternionFromMCDShepperd(Eigen::Matrix3f &m, Eigen::Vector4f &q)
Eigen::VectorXf ekf::RK(float h, const Eigen ::Ref< Eigen::VectorXf > &xk, const Eigen ::Ref< Eigen::VectorXf > &u, Eigen::VectorXf fn(Eigen::VectorXf x, Eigen::VectorXf u))