.TH "Referência do diretório lib/IMU" 3 "Sábado, 20 de Novembro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referência do diretório lib/IMU
.SH SYNOPSIS
.br
.PP
.SS "Arquivos"

.in +1c
.ti -1c
.RI "arquivo \fBIMU\&.cpp\fP"
.br
.ti -1c
.RI "arquivo \fBIMU\&.h\fP"
.br
.ti -1c
.RI "arquivo \fBMETODOSCALIBRACAO\&.h\fP"
.br
.RI "biblioteca contendo algoritmos de calibracao para acelerometro e magnetometro\&. Para correto funcionamento a bibioteca EIGEN deve estar indicada no include abaixo "
.in -1c
