.TH "Referência do diretório lib/GRUPO_QUAT" 3 "Segunda, 25 de Outubro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referência do diretório lib/GRUPO_QUAT
.SH SYNOPSIS
.br
.PP
.SS "Arquivos"

.in +1c
.ti -1c
.RI "arquivo \fBGRUPO_QUAT\&.cpp\fP"
.br
.RI "Cabecalho com funcoes de quaternion\&. "
.ti -1c
.RI "arquivo \fBGRUPO_QUAT\&.h\fP"
.br
.RI "Cabecalho com funcoes de quaternion\&. "
.in -1c
