.TH "Referência do diretório lib/TIME" 3 "Sábado, 20 de Novembro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referência do diretório lib/TIME
.SH SYNOPSIS
.br
.PP
.SS "Arquivos"

.in +1c
.ti -1c
.RI "arquivo \fBTIME\&.cpp\fP"
.br
.RI "Classe para medir Intervalo de tempo entre duas chamadas\&. "
.ti -1c
.RI "arquivo \fBTIME\&.h\fP"
.br
.RI "Classe para medir Intervalo de tempo entre duas chamadas\&. "
.in -1c
