.TH "Referência do diretório lib" 3 "Segunda, 25 de Outubro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referência do diretório lib
.SH SYNOPSIS
.br
.PP
.SS "Diretórios"

.in +1c
.ti -1c
.RI "diretório \fBAQUA\fP"
.br
.ti -1c
.RI "diretório \fBCONTROLE\fP"
.br
.ti -1c
.RI "diretório \fBDRONE\fP"
.br
.ti -1c
.RI "diretório \fBEKF\fP"
.br
.ti -1c
.RI "diretório \fBGRUPO_QUAT\fP"
.br
.ti -1c
.RI "diretório \fBIMU\fP"
.br
.ti -1c
.RI "diretório \fBMOTORES\fP"
.br
.ti -1c
.RI "diretório \fBRICCATI\fP"
.br
.ti -1c
.RI "diretório \fBRPM\fP"
.br
.ti -1c
.RI "diretório \fBSDRE\fP"
.br
.ti -1c
.RI "diretório \fBTELEMETRIA\fP"
.br
.ti -1c
.RI "diretório \fBTIME\fP"
.br
.in -1c
