.TH "Referência do diretório lib/EKF" 3 "Sexta, 17 de Setembro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referência do diretório lib/EKF
.SH SYNOPSIS
.br
.PP
.SS "Arquivos"

.in +1c
.ti -1c
.RI "arquivo \fBEKF\&.cpp\fP"
.br
.RI "Classe que implementa o filtro de Kalman estendido\&. "
.ti -1c
.RI "arquivo \fBEKF\&.h\fP"
.br
.RI "Classe que implementa o filtro de Kalman estendido\&. "
.ti -1c
.RI "arquivo \fBGPS\&.h\fP"
.br
.RI "Simples Cabecalho de funcoes para leituras do GPS Last modified by: roney Last modified time: 31-Aug-2021\&. "
.in -1c
