.TH "Referência do diretório python" 3 "Sábado, 20 de Novembro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referência do diretório python
.SH SYNOPSIS
.br
.PP
.SS "Arquivos"

.in +1c
.ti -1c
.RI "arquivo \fBdrone\&.py\fP"
.br
.ti -1c
.RI "arquivo \fBfuncoesQuaternion\&.py\fP"
.br
.in -1c
