.TH "BASE" 3 "Sexta, 17 de Setembro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BASE
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EKF\&.h>\fP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "float \fBlat\fP"
.br
.ti -1c
.RI "float \fBlon\fP"
.br
.ti -1c
.RI "float \fBhMSL\fP"
.br
.ti -1c
.RI "Eigen::Matrix3f \fBRecef2ned\fP"
.br
.ti -1c
.RI "long \fBrECEF\fP [3]"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Definição na linha 22 do arquivo EKF\&.h\&.
.SH "Campos"
.PP 
.SS "float BASE::hMSL"
Altitude ao nível do mar 
.PP
Definição na linha 28 do arquivo EKF\&.h\&.
.SS "float BASE::lat"
Latitude em Radianos 
.PP
Definição na linha 24 do arquivo EKF\&.h\&.
.SS "float BASE::lon"
Longitude em Radianos 
.PP
Definição na linha 26 do arquivo EKF\&.h\&.
.SS "long BASE::rECEF[3]"
Coordenadas da base no sistema ECEF 
.PP
Definição na linha 32 do arquivo EKF\&.h\&.
.SS "Eigen::Matrix3f BASE::Recef2ned"
Matriz de transformação 
.PP
Definição na linha 30 do arquivo EKF\&.h\&.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
