.TH "lib/CONTROLE/Controle.h" 3 "Sábado, 20 de Novembro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/CONTROLE/Controle.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./DRONE/Drone\&.h'\fP
.br
\fC#include '\&.\&./SDRE/Sdre\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./\&.\&./quadricopterFinal/lib/GRUPO_QUAT/GRUPO_QUAT\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include '\&.\&./READWRITEEIGEN/readWriteEigen\&.h'\fP
.br
\fC#include <eigen3/Eigen/Dense>\fP
.br

.SS "Estruturas de Dados"

.in +1c
.ti -1c
.RI "class \fBControle\fP"
.br
.in -1c
.SS "Definições e Macros"

.in +1c
.ti -1c
.RI "#define \fBDEBUG_CONTROL\fP"
.br
.ti -1c
.RI "#define \fBLOAD_GAINS\fP"
.br
.ti -1c
.RI "#define \fBPRINT_MAT\fP(X)   cout << #X << ':\\n' << X << '\\n'"
.br
.ti -1c
.RI "#define \fBINTEGRAL_CONTROL\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 

.PP
\fBAutor\fP
.RS 4
: Roney Silva (roneydua) 
.RE
.PP
\fBData\fP
.RS 4
: 19-Aug-2021 Email: roneyddasilva@gmail.com Project: quadrirrotorUFABC
.RE
.PP
Last modified by: roneydua Last modified time: 25-Aug-2021 
.PP
Definição no arquivo \fBControle\&.h\fP\&.
.SH "Definições e macros"
.PP 
.SS "#define DEBUG_CONTROL"

.PP
Definição na linha 16 do arquivo Controle\&.h\&.
.SS "#define INTEGRAL_CONTROL"

.PP
Definição na linha 29 do arquivo Controle\&.h\&.
.SS "#define LOAD_GAINS"
Precompilador para leitrua dos ganhos 
.PP
Definição na linha 18 do arquivo Controle\&.h\&.
.SS "#define PRINT_MAT(X)   cout << #X << ':\\n' << X << '\\n'"

.PP
Definição na linha 21 do arquivo Controle\&.h\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
