.TH "python/drone.py" 3 "Sábado, 20 de Novembro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/drone.py
.SH SYNOPSIS
.br
.PP
.SS "Estruturas de Dados"

.in +1c
.ti -1c
.RI "class \fBdrone\&.Drone\fP"
.br
.in -1c
.SS "<em>Namespaces</em>"

.in +1c
.ti -1c
.RI " \fBdrone\fP"
.br
.in -1c
.SS "Variáveis"

.in +1c
.ti -1c
.RI "\fBdrone\&.grav\fP = np\&.array([0\&.0, 0\&.0, 9\&.81])"
.br
.ti -1c
.RI "float \fBdrone\&.Ix\fP = 16\&.83e\-3"
.br
.ti -1c
.RI "float \fBdrone\&.Iy\fP = 16\&.83e\-3"
.br
.ti -1c
.RI "float \fBdrone\&.Iz\fP = 28\&.34e\-3"
.br
.ti -1c
.RI "float \fBdrone\&.kf\fP = 1\&.4351e\-5"
.br
.ti -1c
.RI "float \fBdrone\&.km\fP = 2\&.4086e\-7"
.br
.ti -1c
.RI "float \fBdrone\&.b\fP = 0\&.26"
.br
.ti -1c
.RI "float \fBdrone\&.m\fP = 1\&.03"
.br
.ti -1c
.RI "float \fBdrone\&.Ir\fP = 5\&.0e\-5"
.br
.ti -1c
.RI "float \fBdrone\&.ta\fP = 0\&.03"
.br
.ti -1c
.RI "float \fBdrone\&.DA\fP = 0\&.5"
.br
.in -1c
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
