.TH "drone" 3 "Sexta, 17 de Setembro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drone
.SH SYNOPSIS
.br
.PP
.SS "Estruturas de Dados"

.in +1c
.ti -1c
.RI "class \fBDrone\fP"
.br
.in -1c
.SS "Variáveis"

.in +1c
.ti -1c
.RI "\fBgrav\fP = np\&.array([0\&.0, 0\&.0, 9\&.81])"
.br
.ti -1c
.RI "float \fBIx\fP = 16\&.83e\-3"
.br
.ti -1c
.RI "float \fBIy\fP = 16\&.83e\-3"
.br
.ti -1c
.RI "float \fBIz\fP = 28\&.34e\-3"
.br
.ti -1c
.RI "float \fBkf\fP = 1\&.4351e\-5"
.br
.ti -1c
.RI "float \fBkm\fP = 2\&.4086e\-7"
.br
.ti -1c
.RI "float \fBb\fP = 0\&.26"
.br
.ti -1c
.RI "float \fBm\fP = 1\&.03"
.br
.ti -1c
.RI "float \fBIr\fP = 5\&.0e\-5"
.br
.ti -1c
.RI "float \fBta\fP = 0\&.03"
.br
.ti -1c
.RI "float \fBDA\fP = 0\&.5"
.br
.in -1c
.SH "Variáveis"
.PP 
.SS "float drone\&.b = 0\&.26"

.PP
Definição na linha 20 do arquivo drone\&.py\&.
.SS "float drone\&.DA = 0\&.5"

.PP
Definição na linha 25 do arquivo drone\&.py\&.
.SS "drone\&.grav = np\&.array([0\&.0, 0\&.0, 9\&.81])"

.PP
Definição na linha 11 do arquivo drone\&.py\&.
.SS "float drone\&.Ir = 5\&.0e\-5"

.PP
Definição na linha 22 do arquivo drone\&.py\&.
.SS "float drone\&.Ix = 16\&.83e\-3"

.PP
Definição na linha 13 do arquivo drone\&.py\&.
.SS "float drone\&.Iy = 16\&.83e\-3"

.PP
Definição na linha 14 do arquivo drone\&.py\&.
.SS "float drone\&.Iz = 28\&.34e\-3"

.PP
Definição na linha 15 do arquivo drone\&.py\&.
.SS "float drone\&.kf = 1\&.4351e\-5"

.PP
Definição na linha 17 do arquivo drone\&.py\&.
.SS "float drone\&.km = 2\&.4086e\-7"

.PP
Definição na linha 18 do arquivo drone\&.py\&.
.SS "float drone\&.m = 1\&.03"

.PP
Definição na linha 21 do arquivo drone\&.py\&.
.PP
Referenciado(a) por ekf\&.computeQuaternionFromMCDMarkley() e ekf\&.printEigen()\&.
.SS "float drone\&.ta = 0\&.03"

.PP
Definição na linha 24 do arquivo drone\&.py\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
