.TH "lib/DRONE/Drone.h" 3 "Sábado, 20 de Novembro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/DRONE/Drone.h
.SH SYNOPSIS
.br
.PP
\fC#include 'eigen3/Eigen/Dense'\fP
.br
\fC#include '\&.\&./\&.\&./\&.\&./quadricopterFinal/lib/GRUPO_QUAT/GRUPO_QUAT\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Estruturas de Dados"

.in +1c
.ti -1c
.RI "class \fBDrone\fP"
.br
.in -1c
.SS "Definições e Macros"

.in +1c
.ti -1c
.RI "#define \fBPRINT_MAT\fP(X)   cout << #X << ':\\n' << X << '\\n'"
.br
.in -1c
.SH "Descrição detalhada"
.PP 

.PP
\fBAutor\fP
.RS 4
: Roney Silva <roney> 
.RE
.PP
\fBData\fP
.RS 4
: 16-Aug-2021 Email: roneyddasilva@gmail.com Project: quadrirrotorUFABC
.RE
.PP
Last modified by: roney Last modified time: 25-Aug-2021 
.PP
Definição no arquivo \fBDrone\&.h\fP\&.
.SH "Definições e macros"
.PP 
.SS "#define PRINT_MAT(X)   cout << #X << ':\\n' << X << '\\n'"

.PP
Definição na linha 17 do arquivo Drone\&.h\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
