.TH "lib/EKF/EKF.cpp" 3 "Segunda, 25 de Outubro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/EKF/EKF.cpp \- Classe que implementa o filtro de Kalman estendido\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'EKF\&.h'\fP
.br

.SS "<em>Namespaces</em>"

.in +1c
.ti -1c
.RI " \fBekf\fP"
.br
.RI "Funções genéricas com álgebra de quatérnions e demais\&. "
.in -1c
.SS "Variáveis"

.in +1c
.ti -1c
.RI "\fBAQUA\fP \fBekf::aqua\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Classe que implementa o filtro de Kalman estendido\&. 


.PP
\fBAutor\fP
.RS 4
: Roney Silva (roney) 
.RE
.PP
\fBData\fP
.RS 4
: 16-Aug-2021 Email: roneyddasilva@gmail.com Project: quadrirrotorUFABC
.RE
.PP
Last modified by: roney Last modified time: 01-Sep-2021 
.PP
Definição no arquivo \fBEKF\&.cpp\fP\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
