.TH "lib/EKF/EKF.h" 3 "Sexta, 17 de Setembro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/EKF/EKF.h \- Classe que implementa o filtro de Kalman estendido\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'eigen3/Eigen/Dense'\fP
.br
\fC#include '\&./\&.\&./READWRITEEIGEN/readWriteEigen\&.h'\fP
.br

.SS "Estruturas de Dados"

.in +1c
.ti -1c
.RI "struct \fBBASE\fP"
.br
.ti -1c
.RI "class \fBekf::EKF\fP"
.br
.in -1c
.SS "<em>Namespaces</em>"

.in +1c
.ti -1c
.RI " \fBekf\fP"
.br
.RI "Funções genéricas com álgebra de quatérnions e demais\&. "
.in -1c
.SH "Descrição detalhada"
.PP 
Classe que implementa o filtro de Kalman estendido\&. 


.PP
\fBAutor\fP
.RS 4
: Roney Silva (roney) 
.RE
.PP
\fBData\fP
.RS 4
: 16-Aug-2021 Email: roneyddasilva@gmail.com Project: quadrirrotorUFABC
.RE
.PP
Last modified by: roney Last modified time: 01-Sep-2021 
.PP
Definição no arquivo \fBEKF\&.h\fP\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
