.TH "python/funcoesQuaternion.py" 3 "Sábado, 20 de Novembro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/funcoesQuaternion.py
.SH SYNOPSIS
.br
.PP
.SS "<em>Namespaces</em>"

.in +1c
.ti -1c
.RI " \fBfuncoesQuaternion\fP"
.br
.in -1c
.SS "Funções"

.in +1c
.ti -1c
.RI "def \fBfuncoesQuaternion\&.screwMatrix\fP (quat)"
.br
.ti -1c
.RI "def \fBfuncoesQuaternion\&.matrixQ\fP (quat, right=False)"
.br
.ti -1c
.RI "def \fBfuncoesQuaternion\&.matrixS\fP (quat, right=False)"
.br
.ti -1c
.RI "def \fBfuncoesQuaternion\&.MultQuat\fP (r, q, p)"
.br
.ti -1c
.RI "def \fBfuncoesQuaternion\&.conj\fP (q)"
.br
.ti -1c
.RI "def \fBfuncoesQuaternion\&.quat2Euler\fP (q, deg=0)"
.br
.ti -1c
.RI "def \fBfuncoesQuaternion\&.rotationMatrix\fP (q)"
.br
.ti -1c
.RI "def \fBfuncoesQuaternion\&.eulerQuaternion\fP (yaw, pitch, roll, deg=True)"
.br
.in -1c
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
