.TH "hack" 3 "Segunda, 25 de Outubro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hack \- Listas de Hack 

.IP "\fBGlobal \fBekf::EKF::begin\fP (float dt)\fP" 1c

.br
 \fBaccel\fP, \fBgyro\fP e \fBmag\fP são ponteiros\&. Quando as medidas são atualizadas na biblioteca \fBIMU\fP, o vetor é modificado na \fBEKF\fP\&. 
.PP

