.TH "src/IBusBM.h" 3 "Sábado, 20 de Novembro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/IBusBM.h
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br
\fC#include <inttypes\&.h>\fP
.br

.SS "Estruturas de Dados"

.in +1c
.ti -1c
.RI "class \fBIBusBM\fP"
.br
.ti -1c
.RI "union \fBIBusBM::ControlUnion\fP"
.br
.ti -1c
.RI "struct \fBIBusBM::sensorinfo\fP"
.br
.in -1c
.SS "Definições e Macros"

.in +1c
.ti -1c
.RI "#define \fBIBUSS_INTV\fP   0x00"
.br
.ti -1c
.RI "#define \fBIBUSS_TEMP\fP   0x01"
.br
.ti -1c
.RI "#define \fBIBUSS_RPM\fP   0x02"
.br
.ti -1c
.RI "#define \fBIBUSS_EXTV\fP   0x03"
.br
.ti -1c
.RI "#define \fBIBUS_PRESS\fP   0x41"
.br
.ti -1c
.RI "#define \fBIBUS_SERVO\fP   0xfd"
.br
.ti -1c
.RI "#define \fBIBUSBM_NOTIMER\fP   \-1"
.br
.in -1c
.SH "Definições e macros"
.PP 
.SS "#define IBUS_PRESS   0x41"

.PP
Definição na linha 29 do arquivo IBusBM\&.h\&.
.SS "#define IBUS_SERVO   0xfd"

.PP
Definição na linha 30 do arquivo IBusBM\&.h\&.
.SS "#define IBUSBM_NOTIMER   \-1"

.PP
Definição na linha 52 do arquivo IBusBM\&.h\&.
.SS "#define IBUSS_EXTV   0x03"

.PP
Definição na linha 28 do arquivo IBusBM\&.h\&.
.SS "#define IBUSS_INTV   0x00"

.PP
Definição na linha 25 do arquivo IBusBM\&.h\&.
.SS "#define IBUSS_RPM   0x02"

.PP
Definição na linha 27 do arquivo IBusBM\&.h\&.
.SS "#define IBUSS_TEMP   0x01"

.PP
Definição na linha 26 do arquivo IBusBM\&.h\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
