.TH "IBusBM::ControlUnion" 3 "Segunda, 25 de Outubro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IBusBM::ControlUnion
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IBusBM\&.h>\fP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "uint16_t \fBchannel\fP [14]"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint16_t \fBdX\fP"
.br
.ti -1c
.RI "   uint16_t \fBdY\fP"
.br
.ti -1c
.RI "   uint16_t \fBdZ\fP"
.br
.ti -1c
.RI "   uint16_t \fBdPsi\fP"
.br
.ti -1c
.RI "   uint16_t \fBemergency\fP"
.br
.ti -1c
.RI "   uint16_t \fBcalibration\fP"
.br
.ti -1c
.RI "   uint16_t \fBadjustQuat\fP"
.br
.ti -1c
.RI "   uint16_t \fBadjustQrAngular\fP"
.br
.ti -1c
.RI "   uint16_t \fBcontrol_mode\fP"
.br
.ti -1c
.RI "   uint16_t \fBswd\fP"
.br
.ti -1c
.RI "   uint16_t \fBreserved\fP [4]"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Definição na linha 71 do arquivo IBusBM\&.h\&.
.SH "Campos"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "uint16_t IBusBM::ControlUnion::adjustQrAngular"
Potenciometro vrb\&. 
.PP
Definição na linha 89 do arquivo IBusBM\&.h\&.
.PP
Referenciado(a) por xTaskContol()\&.
.SS "uint16_t IBusBM::ControlUnion::adjustQuat"
Potenciometro vra\&. Limitador manual do valor máximo da empuxo total 
.PP
Definição na linha 87 do arquivo IBusBM\&.h\&.
.PP
Referenciado(a) por xTaskContol()\&.
.SS "uint16_t IBusBM::ControlUnion::calibration"
Botao swb 
.PP
Definição na linha 85 do arquivo IBusBM\&.h\&.
.PP
Referenciado(a) por xTaskSetupFiltro()\&.
.SS "uint16_t IBusBM::ControlUnion::channel[14]"

.PP
Definição na linha 72 do arquivo IBusBM\&.h\&.
.PP
Referenciado(a) por IBusBM::loop() e IBusBM::readChannel()\&.
.SS "uint16_t IBusBM::ControlUnion::control_mode"
Botao swc NOTE: Há três posições 
.PP
Definição na linha 91 do arquivo IBusBM\&.h\&.
.SS "uint16_t IBusBM::ControlUnion::dPsi"
Variacao do angulo psi 
.PP
Definição na linha 81 do arquivo IBusBM\&.h\&.
.PP
Referenciado(a) por xTaskContol()\&.
.SS "uint16_t IBusBM::ControlUnion::dX"
Velocidade em x m/s^2 
.PP
Definição na linha 75 do arquivo IBusBM\&.h\&.
.PP
Referenciado(a) por xTaskContol()\&.
.SS "uint16_t IBusBM::ControlUnion::dY"
Velocidade em y m/s^2 
.PP
Definição na linha 77 do arquivo IBusBM\&.h\&.
.PP
Referenciado(a) por xTaskContol()\&.
.SS "uint16_t IBusBM::ControlUnion::dZ"
Velocidade em z m/s^2 
.PP
Definição na linha 79 do arquivo IBusBM\&.h\&.
.PP
Referenciado(a) por xTaskContol()\&.
.SS "uint16_t IBusBM::ControlUnion::emergency"
Botao swa 
.PP
Definição na linha 83 do arquivo IBusBM\&.h\&.
.PP
Referenciado(a) por emergencyMethods(), setup() e xTaskContol()\&.
.SS "uint16_t IBusBM::ControlUnion::reserved[4]"
NAÕ USADO 
.PP
Definição na linha 95 do arquivo IBusBM\&.h\&.
.SS "uint16_t IBusBM::ControlUnion::swd"
Botao swd 
.PP
Definição na linha 93 do arquivo IBusBM\&.h\&.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
