.TH "IBusBM::sensorinfo" 3 "Segunda, 25 de Outubro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IBusBM::sensorinfo
.SH SYNOPSIS
.br
.PP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "uint8_t \fBsensorType\fP"
.br
.ti -1c
.RI "uint8_t \fBsensorLength\fP"
.br
.ti -1c
.RI "int32_t \fBsensorValue\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Definição na linha 130 do arquivo IBusBM\&.h\&.
.SH "Campos"
.PP 
.SS "uint8_t IBusBM::sensorinfo::sensorLength"

.PP
Definição na linha 132 do arquivo IBusBM\&.h\&.
.PP
Referenciado(a) por IBusBM::addSensor() e IBusBM::loop()\&.
.SS "uint8_t IBusBM::sensorinfo::sensorType"

.PP
Definição na linha 131 do arquivo IBusBM\&.h\&.
.PP
Referenciado(a) por IBusBM::addSensor() e IBusBM::loop()\&.
.SS "int32_t IBusBM::sensorinfo::sensorValue"

.PP
Definição na linha 133 do arquivo IBusBM\&.h\&.
.PP
Referenciado(a) por IBusBM::addSensor(), IBusBM::loop() e IBusBM::setSensorMeasurement()\&.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
