.TH "src/IBusBM.cpp" 3 "Segunda, 25 de Outubro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/IBusBM.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'IBusBM\&.h'\fP
.br
\fC#include <Arduino\&.h>\fP
.br

.SS "Funções"

.in +1c
.ti -1c
.RI "void \fBonTimer\fP ()"
.br
.in -1c
.SS "Variáveis"

.in +1c
.ti -1c
.RI "\fBIBusBM\fP * \fBIBusBMfirst\fP = NULL"
.br
.in -1c
.SH "Funções"
.PP 
.SS "void onTimer ()"

.PP
Definição na linha 44 do arquivo IBusBM\&.cpp\&.
.PP
.nf
44                {
45   if (IBusBMfirst)
46     IBusBMfirst->loop(); // gets new servo values if available and process any
47                          // sensor data
48 }
.fi
.PP
Referencias IBusBMfirst e IBusBM::loop()\&.
.PP
Referenciado(a) por IBusBM::begin()\&.
.SH "Variáveis"
.PP 
.SS "\fBIBusBM\fP* IBusBMfirst = NULL"

.PP
Definição na linha 32 do arquivo IBusBM\&.cpp\&.
.PP
Referenciado(a) por IBusBM::begin() e onTimer()\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
