.TH "lib/IMU/IMU.h" 3 "Sábado, 20 de Novembro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/IMU/IMU.h
.SH SYNOPSIS
.br
.PP
\fC#include 'METODOSCALIBRACAO\&.h'\fP
.br
\fC#include <Arduino\&.h>\fP
.br
\fC#include <Wire\&.h>\fP
.br
\fC#include <eigen3/Eigen/Dense>\fP
.br

.SS "Estruturas de Dados"

.in +1c
.ti -1c
.RI "class \fBIMU\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 

.PP
\fBAutor\fP
.RS 4
: roney 
.RE
.PP
\fBData\fP
.RS 4
: 2021-05-03T16:29:30-03:00 email: roneyddasilva@gmail.com
.RE
.PP
biblioteca criada com base na biblioteca dinivel no GitHub : https://github.com/bolderflight/MPU9250 
.PP
Definição no arquivo \fBIMU\&.h\fP\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
