.TH "lib/IMU/IMU.cpp" 3 "Segunda, 25 de Outubro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/IMU/IMU.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'IMU\&.h'\fP
.br
\fC#include 'Arduino\&.h'\fP
.br

.SH "Descrição detalhada"
.PP 

.PP
\fBAutor\fP
.RS 4
: roney 
.RE
.PP
\fBData\fP
.RS 4
: 2021-05-03T16:29:30-03:00 email: roneyddasilva@gmail.com
.RE
.PP
Last modified by: roney Last modified time: 2021-07-19T18:32:20-03:00 
.PP
Definição no arquivo \fBIMU\&.cpp\fP\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
