.TH "lib/IMU/METODOSCALIBRACAO.h" 3 "Segunda, 25 de Outubro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/IMU/METODOSCALIBRACAO.h \- biblioteca contendo algoritmos de calibracao para acelerometro e magnetometro\&. Para correto funcionamento a bibioteca EIGEN deve estar indicada no include abaixo  

.SH SYNOPSIS
.br
.PP
\fC#include <eigen3/Eigen/Dense>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <Arduino\&.h>\fP
.br

.SS "Estruturas de Dados"

.in +1c
.ti -1c
.RI "class \fBMETODOSCALIBRACAO\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
biblioteca contendo algoritmos de calibracao para acelerometro e magnetometro\&. Para correto funcionamento a bibioteca EIGEN deve estar indicada no include abaixo 


.PP
\fBAutor\fP
.RS 4
: Roney Silva (roney) 
.RE
.PP
\fBData\fP
.RS 4
: 16-Aug-2021 Email: roneyddasilva@gmail.com Project: quadrirrotorUFABC
.RE
.PP
Last modified by: roney Last modified time: 01-Sep-2021 
.PP
Definição no arquivo \fBMETODOSCALIBRACAO\&.h\fP\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
