.TH "MOTOR_PINS" 3 "Sábado, 20 de Novembro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MOTOR_PINS \- Pinos de conexão dos motores\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PARAMETROS\&.h>\fP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "const gpio_num_t \fBmotor_1\fP = GPIO_NUM_18"
.br
.ti -1c
.RI "const gpio_num_t \fBmotor_2\fP = GPIO_NUM_32"
.br
.ti -1c
.RI "const gpio_num_t \fBmotor_3\fP = GPIO_NUM_33"
.br
.ti -1c
.RI "const gpio_num_t \fBmotor_4\fP = GPIO_NUM_14"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Pinos de conexão dos motores\&. 
.PP
Definição na linha 17 do arquivo PARAMETROS\&.h\&.
.SH "Campos"
.PP 
.SS "const gpio_num_t MOTOR_PINS::motor_1 = GPIO_NUM_18"
Pino do motor 1 
.PP
Definição na linha 19 do arquivo PARAMETROS\&.h\&.
.PP
Referenciado(a) por xTaskContol()\&.
.SS "const gpio_num_t MOTOR_PINS::motor_2 = GPIO_NUM_32"
Pino do motor 2 
.PP
Definição na linha 21 do arquivo PARAMETROS\&.h\&.
.PP
Referenciado(a) por xTaskContol()\&.
.SS "const gpio_num_t MOTOR_PINS::motor_3 = GPIO_NUM_33"
Pino do motor 3 
.PP
Definição na linha 23 do arquivo PARAMETROS\&.h\&.
.PP
Referenciado(a) por xTaskContol()\&.
.SS "const gpio_num_t MOTOR_PINS::motor_4 = GPIO_NUM_14"
Pino do motor 4 
.PP
Definição na linha 25 do arquivo PARAMETROS\&.h\&.
.PP
Referenciado(a) por xTaskContol()\&.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
