.TH "NAV_POSECEF_STRUCT" 3 "Sábado, 20 de Novembro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NAV_POSECEF_STRUCT
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GPS\&.h>\fP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "unsigned char \fBcls\fP"
.br
.ti -1c
.RI "unsigned char \fBid\fP"
.br
.ti -1c
.RI "unsigned short \fBlen\fP"
.br
.ti -1c
.RI "unsigned long \fBiTOW\fP"
.br
.ti -1c
.RI "long \fBecefX\fP"
.br
.ti -1c
.RI "long \fBecefY\fP"
.br
.ti -1c
.RI "long \fBecefZ\fP"
.br
.ti -1c
.RI "long \fBpAcc\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Definição na linha 59 do arquivo GPS\&.h\&.
.SH "Campos"
.PP 
.SS "unsigned char NAV_POSECEF_STRUCT::cls"

.PP
Definição na linha 60 do arquivo GPS\&.h\&.
.SS "long NAV_POSECEF_STRUCT::ecefX"
ECEF X coordinate (cm) 
.PP
Definição na linha 65 do arquivo GPS\&.h\&.
.PP
Referenciado(a) por gps_imprime()\&.
.SS "long NAV_POSECEF_STRUCT::ecefY"
ECEF Y coordinate (cm) 
.PP
Definição na linha 67 do arquivo GPS\&.h\&.
.PP
Referenciado(a) por gps_imprime()\&.
.SS "long NAV_POSECEF_STRUCT::ecefZ"
ECEF Z coordinate (cm) 
.PP
Definição na linha 69 do arquivo GPS\&.h\&.
.PP
Referenciado(a) por gps_imprime()\&.
.SS "unsigned char NAV_POSECEF_STRUCT::id"

.PP
Definição na linha 61 do arquivo GPS\&.h\&.
.SS "unsigned long NAV_POSECEF_STRUCT::iTOW"

.PP
Definição na linha 63 do arquivo GPS\&.h\&.
.PP
Referenciado(a) por gps_imprime()\&.
.SS "unsigned short NAV_POSECEF_STRUCT::len"

.PP
Definição na linha 62 do arquivo GPS\&.h\&.
.SS "long NAV_POSECEF_STRUCT::pAcc"

.PP
Definição na linha 70 do arquivo GPS\&.h\&.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
