.TH "PacketData" 3 "Sábado, 20 de Novembro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PacketData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GPS\&.h>\fP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "long \fBlon\fP"
.br
.ti -1c
.RI "long \fBlat\fP"
.br
.ti -1c
.RI "int32_t \fBaltitude\fP"
.br
.ti -1c
.RI "long \fBvelN\fP"
.br
.ti -1c
.RI "long \fBvelE\fP"
.br
.ti -1c
.RI "long \fBvelD\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Definição na linha 137 do arquivo GPS\&.h\&.
.SH "Campos"
.PP 
.SS "int32_t PacketData::altitude"

.PP
Definição na linha 140 do arquivo GPS\&.h\&.
.SS "long PacketData::lat"

.PP
Definição na linha 139 do arquivo GPS\&.h\&.
.SS "long PacketData::lon"

.PP
Definição na linha 138 do arquivo GPS\&.h\&.
.SS "long PacketData::velD"

.PP
Definição na linha 143 do arquivo GPS\&.h\&.
.SS "long PacketData::velE"

.PP
Definição na linha 142 do arquivo GPS\&.h\&.
.SS "long PacketData::velN"

.PP
Definição na linha 141 do arquivo GPS\&.h\&.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
