.TH "src/PARAMETROS.h" 3 "Segunda, 25 de Outubro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/PARAMETROS.h \- \fCSobre os conversores digitais analógicos\fP  

.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br

.SS "Estruturas de Dados"

.in +1c
.ti -1c
.RI "struct \fBMOTOR_PINS\fP"
.br
.RI "Pinos de conexão dos motores\&. "
.ti -1c
.RI "struct \fBRPM_PIN\fP"
.br
.RI "Pinos de contadores de RPM\&. "
.in -1c
.SS "Variáveis"

.in +1c
.ti -1c
.RI "gpio_num_t \fBonboard_led\fP = GPIO_NUM_5"
.br
.ti -1c
.RI "const int8_t \fBpin_rx_controle\fP = 13"
.br
.ti -1c
.RI "const uint16_t \fBdtTelemetry\fP = 12"
.br
.ti -1c
.RI "const TickType_t \fBxdtTelemetry\fP = pdMS_TO_TICKS(\fBdtTelemetry\fP)"
.br
.ti -1c
.RI "const uint16_t \fBdtControle\fP = 15"
.br
.ti -1c
.RI "const TickType_t \fBxdtControle\fP = pdMS_TO_TICKS(\fBdtControle\fP)"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
\fCSobre os conversores digitais analógicos\fP 


.PP
\fBAutor\fP
.RS 4
: roney 
.RE
.PP
\fBData\fP
.RS 4
: 2021-05-12T13:52:07-03:00 email: roneyddasilva@gmail.com 
.RE
.PP

.PP
Definição no arquivo \fBPARAMETROS\&.h\fP\&.
.SH "Variáveis"
.PP 
.SS "const uint16_t dtControle = 15"
Período de cotrole em milissegundos 
.PP
Definição na linha 51 do arquivo PARAMETROS\&.h\&.
.PP
Referenciado(a) por xTaskContol()\&.
.SS "const uint16_t dtTelemetry = 12"
Período de temetria em milissegundos 
.PP
Definição na linha 47 do arquivo PARAMETROS\&.h\&.
.PP
Referenciado(a) por setup() e xTaskSetupFiltro()\&.
.SS "gpio_num_t onboard_led = GPIO_NUM_5"
Led onboard para sinalização\&. 
.PP
Definição na linha 43 do arquivo PARAMETROS\&.h\&.
.PP
Referenciado(a) por blindLED(), setup(), turnOffLed() e turnOnLed()\&.
.SS "const int8_t pin_rx_controle = 13"
Porta Rx do controle 
.PP
Definição na linha 45 do arquivo PARAMETROS\&.h\&.
.PP
Referenciado(a) por setup()\&.
.SS "const TickType_t xdtControle = pdMS_TO_TICKS(\fBdtControle\fP)"
Periodo de telemetria em Ticks 
.PP
Definição na linha 53 do arquivo PARAMETROS\&.h\&.
.PP
Referenciado(a) por xTaskContol()\&.
.SS "const TickType_t xdtTelemetry = pdMS_TO_TICKS(\fBdtTelemetry\fP)"
Periodo de telemetria em Ticks 
.PP
Definição na linha 49 do arquivo PARAMETROS\&.h\&.
.PP
Referenciado(a) por xTaskLoopFilter()\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
