.TH "lib/RICCATI/Riccati.h" 3 "Sábado, 20 de Novembro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/RICCATI/Riccati.h
.SH SYNOPSIS
.br
.PP
\fC#include 'eigen3/Eigen/Dense'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Estruturas de Dados"

.in +1c
.ti -1c
.RI "class \fBRiccati\fP"
.br
.in -1c
.SS "Definições e Macros"

.in +1c
.ti -1c
.RI "#define \fBDEBUG\fP"
.br
.ti -1c
.RI "#define \fBPRINT_MAT\fP(X)   cout << #X << ':\\n' << X << '\\n'"
.br
.in -1c
.SH "Descrição detalhada"
.PP 

.PP
\fBAutor\fP
.RS 4
roneydua (roneyddasilva@gmail.com) 
.RE
.PP
\fBVersão\fP
.RS 4
0\&.1 
.RE
.PP
\fBData\fP
.RS 4
2021-09-19
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2021 
.RE
.PP

.PP
Definição no arquivo \fBRiccati\&.h\fP\&.
.SH "Definições e macros"
.PP 
.SS "#define DEBUG"

.PP
Definição na linha 16 do arquivo Riccati\&.h\&.
.SS "#define PRINT_MAT(X)   cout << #X << ':\\n' << X << '\\n'"

.PP
Definição na linha 19 do arquivo Riccati\&.h\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
