.TH "lib/RICCATI/Riccati.h" 3 "Sexta, 17 de Setembro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/RICCATI/Riccati.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Arduino\&.h'\fP
.br
\fC#include 'GRUPO_QUAT\&.h'\fP
.br
\fC#include <eigen3/Eigen/Dense>\fP
.br

.SS "Estruturas de Dados"

.in +1c
.ti -1c
.RI "class \fBRiccati\fP"
.br
.in -1c
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
