.TH "lib/RPM/rpm.h" 3 "Sexta, 17 de Setembro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/RPM/rpm.h
.SH SYNOPSIS
.br
.PP
\fC#include 'driver/pcnt\&.h'\fP
.br
\fC#include <Arduino\&.h>\fP
.br

.SS "Estruturas de Dados"

.in +1c
.ti -1c
.RI "class \fBRpm\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 

.PP
\fBAutor\fP
.RS 4
: Roney Silva (roneydua) 
.RE
.PP
\fBData\fP
.RS 4
: 16-Aug-2021 Email: roneyddasilva@gmail.com Project: quadrirrotorUFABC
.RE
.PP
Last modified by: roneydua Last modified time: 25-Aug-2021 
.PP
Definição no arquivo \fBrpm\&.h\fP\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
