.TH "RPM_PIN" 3 "Segunda, 25 de Outubro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RPM_PIN \- Pinos de contadores de RPM\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PARAMETROS\&.h>\fP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "const gpio_num_t \fBpin_rpm_motor_1\fP = GPIO_NUM_18"
.br
.ti -1c
.RI "const gpio_num_t \fBpin_rpm_motor_2\fP = GPIO_NUM_34"
.br
.ti -1c
.RI "const gpio_num_t \fBpin_rpm_motor_3\fP = GPIO_NUM_25"
.br
.ti -1c
.RI "const gpio_num_t \fBpin_rpm_motor_4\fP = GPIO_NUM_12"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Pinos de contadores de RPM\&. 
.PP
Definição na linha 32 do arquivo PARAMETROS\&.h\&.
.SH "Campos"
.PP 
.SS "const gpio_num_t RPM_PIN::pin_rpm_motor_1 = GPIO_NUM_18"
Pino de leitura do RPM do motor 1 
.PP
Definição na linha 34 do arquivo PARAMETROS\&.h\&.
.SS "const gpio_num_t RPM_PIN::pin_rpm_motor_2 = GPIO_NUM_34"
Pino de leitura do RPM do motor 2 
.PP
Definição na linha 36 do arquivo PARAMETROS\&.h\&.
.SS "const gpio_num_t RPM_PIN::pin_rpm_motor_3 = GPIO_NUM_25"
Pino de leitura do RPM do motor 3 
.PP
Definição na linha 38 do arquivo PARAMETROS\&.h\&.
.SS "const gpio_num_t RPM_PIN::pin_rpm_motor_4 = GPIO_NUM_12"
Pino de leitura do RPM do 4 
.PP
Definição na linha 40 do arquivo PARAMETROS\&.h\&.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
