.TH "lib/SDRE/Sdre.h" 3 "Sexta, 17 de Setembro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/SDRE/Sdre.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./RICCATI/Riccati\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <eigen3/Eigen/Dense>\fP
.br

.SS "Estruturas de Dados"

.in +1c
.ti -1c
.RI "class \fBSdre\fP"
.br
.in -1c
.SS "Definições e Macros"

.in +1c
.ti -1c
.RI "#define \fBPRINT_MAT\fP(X)   cout << #X << ':\\n' << X << '\\n'"
.br
.in -1c
.SH "Definições e macros"
.PP 
.SS "#define PRINT_MAT(X)   cout << #X << ':\\n' << X << '\\n'"

.PP
Definição na linha 16 do arquivo Sdre\&.h\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
