.TH "lib/TELEMETRIA/TELEMETRIA.cpp" 3 "Segunda, 25 de Outubro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/TELEMETRIA/TELEMETRIA.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'TELEMETRIA\&.h'\fP
.br
\fC#include 'Arduino\&.h'\fP
.br

.SH "Descrição detalhada"
.PP 

.PP
\fBAutor\fP
.RS 4
: roney 
.RE
.PP
\fBData\fP
.RS 4
: 2021-05-07T10:25:15-03:00 email: roneyddasilva@gmail.com
.RE
.PP
Last modified by: roney Last modified time: 2021-05-07T10:27:01-03:00 
.PP
Definição no arquivo \fBTELEMETRIA\&.cpp\fP\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
