.TH "lib/TELEMETRIA/TELEMETRIA.h" 3 "Sábado, 20 de Novembro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/TELEMETRIA/TELEMETRIA.h
.SH SYNOPSIS
.br
.PP
\fC#include <eigen3/Eigen/Dense>\fP
.br
\fC#include 'Arduino\&.h'\fP
.br
\fC#include 'WiFi\&.h'\fP
.br
\fC#include 'esp_now\&.h'\fP
.br

.SS "Estruturas de Dados"

.in +1c
.ti -1c
.RI "class \fBTELEMETRIA\fP"
.br
.ti -1c
.RI "struct \fBTELEMETRIA::IMU_DATA\fP"
.br
.RI "Estrutura de mensagem\&. "
.ti -1c
.RI "struct \fBTELEMETRIA::MENSAGEM\fP"
.br
.RI "Mensagem de texto para envio\&. "
.in -1c
.SS "Definições e Macros"

.in +1c
.ti -1c
.RI "#define \fBDEBUG_BY_SERIAL\fP"
.br
.ti -1c
.RI "#define \fBDATA_SIZE\fP   26"
.br
.in -1c
.SH "Definições e macros"
.PP 
.SS "#define DATA_SIZE   26"

.PP
Definição na linha 20 do arquivo TELEMETRIA\&.h\&.
.SS "#define DEBUG_BY_SERIAL"

.PP
\fBAutor\fP
.RS 4
: roney 
.RE
.PP
\fBData\fP
.RS 4
: 2021-05-07T10:25:15-03:00 email: roneyddasilva@gmail.com @File: \fBTELEMETRIA\&.h\fP Last modified by: roney Last modified time: 2021-07-19T18:33:13-03:00 
.RE
.PP

.PP
Definição na linha 19 do arquivo TELEMETRIA\&.h\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
