.TH "TELEMETRIA::MENSAGEM" 3 "Segunda, 25 de Outubro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TELEMETRIA::MENSAGEM \- Mensagem de texto para envio\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TELEMETRIA\&.h>\fP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "char \fBinfo\fP [35]"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Mensagem de texto para envio\&. 

Tamanho 35 Bytes 
.PP
Definição na linha 54 do arquivo TELEMETRIA\&.h\&.
.SH "Campos"
.PP 
.SS "char TELEMETRIA::MENSAGEM::info[35]"

.PP
Definição na linha 55 do arquivo TELEMETRIA\&.h\&.
.PP
Referenciado(a) por TELEMETRIA::enviaMensagem()\&.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
