.TH "lib/TIME/TIME.cpp" 3 "Sábado, 20 de Novembro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/TIME/TIME.cpp \- Classe para medir Intervalo de tempo entre duas chamadas\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'TIME\&.h'\fP
.br
\fC#include <Arduino\&.h>\fP
.br

.SH "Descrição detalhada"
.PP 
Classe para medir Intervalo de tempo entre duas chamadas\&. 


.PP
\fBAutor\fP
.RS 4
Roney D da Silva 
.RE
.PP
\fBData\fP
.RS 4
5 May 2021 
.RE
.PP
\fBCopyright\fP
.RS 4
2021 Roney D da Silva Email: roneyddasilva@gmail.com 
.RE
.PP

.PP
Definição no arquivo \fBTIME\&.cpp\fP\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
