.TH "TIME" 3 "Sábado, 20 de Novembro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIME
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TIME\&.h>\fP
.SS "Membros Públicos"

.in +1c
.ti -1c
.RI "\fBTIME\fP ()"
.br
.RI "Instância da classe Time\&. "
.ti -1c
.RI "float \fBcomputeElapsedTime\fP ()"
.br
.RI "Retorna o valor do tempo decorrido desde a última requisição\&. "
.ti -1c
.RI "void \fBbegin\fP ()"
.br
.in -1c
.SS "Atributos Privados"

.in +1c
.ti -1c
.RI "uint8_t \fBtimeVectorIndex\fP = 0"
.br
.ti -1c
.RI "uint64_t \fBtimeVector\fP [2] = {}"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Definição na linha 14 do arquivo TIME\&.h\&.
.SH "Construtores e Destrutores"
.PP 
.SS "TIME::TIME ()"

.PP
Instância da classe Time\&. Utilizando o temporizador de alta resolução\&. \fCtimer esp_timer_get_time()\fP 
.PP
Definição na linha 17 do arquivo TIME\&.cpp\&.
.PP
.nf
17 { begin(); }
.fi
.PP
Referencias begin()\&.
.SH "Funções membros"
.PP 
.SS "void TIME::begin ()"
Inicialização da classe Time\&. 
.PP
Definição na linha 21 do arquivo TIME\&.cpp\&.
.PP
.nf
21                  {
22   timeVector[0] = esp_timer_get_time();
23   timeVectorIndex = 0;
24 }
.fi
.PP
Referencias timeVector e timeVectorIndex\&.
.PP
Referenciado(a) por ekf::EKF::begin() e TIME()\&.
.SS "float TIME::computeElapsedTime ()"

.PP
Retorna o valor do tempo decorrido desde a última requisição\&. 
.PP
\fBRetorna\fP
.RS 4
float de tempo decorrido em segundos\&. 
.RE
.PP
\fBObservação\fP
.RS 4
\fCesp_timer_get_time()\fP Computa o tempo decorrido em ms desde a Inicialização\&. 
.RE
.PP

.PP
Definição na linha 32 do arquivo TIME\&.cpp\&.
.PP
.nf
32                                {
33   timeVectorIndex = 1 - timeVectorIndex;
34   timeVector[timeVectorIndex] = esp_timer_get_time();
35   return 1e-6 *
36          float((timeVector[timeVectorIndex] - timeVector[1 - timeVectorIndex]));
37 }
.fi
.PP
Referencias timeVector e timeVectorIndex\&.
.SH "Campos"
.PP 
.SS "uint64_t TIME::timeVector[2] = {}\fC [private]\fP"
Vetor com as ultimas duas medidas\&. 
.PP
Definição na linha 25 do arquivo TIME\&.h\&.
.PP
Referenciado(a) por begin() e computeElapsedTime()\&.
.SS "uint8_t TIME::timeVectorIndex = 0\fC [private]\fP"
Indice do vetor\&. 
.PP
Definição na linha 23 do arquivo TIME\&.h\&.
.PP
Referenciado(a) por begin() e computeElapsedTime()\&.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Quadrirrotor a partir do código-fonte\&.
