.TH "todo" 3 "Segunda, 25 de Outubro de 2021" "Quadrirrotor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Lista de atividades futuras 

.IP "\fBGlobal \fBIMU::_biasAccel\fP \fP" 1c
A MARG eh capaz de registrar os bias/Offset nos resgistradores\&. Feito isso as medidas 
.br
  
.IP "\fBGlobal \fBRiccati::dareInteration\fP (const float &tolerance=1\&.0E-4, const uint16_t iter_max=50)\fP" 1c
Testar a influencia em armazenar a matrix A\&.transpose()\&. 
.PP

